/* =========================================================================
 * The Flow — Türkçe
 *
 * Keys are the English sentence exactly as the app renders it. {} stands where
 * a value is dropped in; the translation may reorder them as {1} {2} when
 * Turkish word order needs it, and must keep every one of them.
 *
 * Two rules worth holding to while adding entries:
 *
 * A single word here will only ever be used inside a button, a tab, a heading
 * or another piece of furniture — never in a list of things somebody wrote.
 * That is deliberate, and it is why "Read" can safely mean "Oku" without
 * renaming anybody's habit.
 *
 * And the register is the app's own: direct, plain, second person, no
 * management-speak. "Kaydet", not "Kaydetmek üzere işlemi onaylayınız".
 * ====================================================================== */

(function () {
'use strict';

/* ---------------------------------------------------------------- rules ---
 * A dictionary can only hold sentences somebody wrote down. Dates are not
 * that: "Thu 17 Sept" is assembled from a calendar, and there are as many of
 * them as there are days. So these are shapes rather than strings.
 *
 * Every one is anchored to the whole value, which is the safety rule. A rule
 * that must match "Thu 17 Sept" from its first character to its last cannot
 * also fire on a journal entry that happens to mention Thursday — and a
 * journal entry is exactly what must never be rewritten.
 *
 * Turkish puts the day number first and the weekday last: 17 Eyl Per.
 * ------------------------------------------------------------------------ */

var DOW = { Mon:'Pzt', Tue:'Sal', Wed:'Çar', Thu:'Per', Fri:'Cu', Sat:'Cmt', Sun:'Paz' };
var DOW_LONG = { Monday:'Pazartesi', Tuesday:'Salı', Wednesday:'Çarşamba', Thursday:'Perşembe',
                 Friday:'Cuma', Saturday:'Cumartesi', Sunday:'Pazar' };
var MON = { Jan:'Oca', Feb:'Şub', Mar:'Mar', Apr:'Nis', May:'May', Jun:'Haz',
            Jul:'Tem', Aug:'Ağu', Sep:'Eyl', Sept:'Eyl', Oct:'Eki', Nov:'Kas', Dec:'Ara' };
var MON_LONG = { January:'Ocak', February:'Şubat', March:'Mart', April:'Nisan', May:'Mayıs',
                 June:'Haziran', July:'Temmuz', August:'Ağustos', September:'Eylül',
                 October:'Ekim', November:'Kasım', December:'Aralık' };

var D = '(Mon|Tue|Wed|Thu|Fri|Sat|Sun)';
var DL = '(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)';
var M = '(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sept|Sep|Oct|Nov|Dec)';
var ML = '(January|February|March|April|May|June|July|August|September|October|November|December)';

var RULES = [
  /* Thu 17 Sept  ->  17 Eyl Per */
  { rx: new RegExp('^' + D + ' (\\d{1,2}) ' + M + '$'),
    to: function (m) { return m[2] + ' ' + MON[m[3]] + ' ' + DOW[m[1]]; } },

  /* Tuesday 15 September 2026  ->  15 Eylül 2026 Salı */
  { rx: new RegExp('^' + DL + ' (\\d{1,2}) ' + ML + '( \\d{4})?$'),
    to: function (m) { return m[2] + ' ' + MON_LONG[m[3]] + (m[4] || '') + ' ' + DOW_LONG[m[1]]; } },

  /* TUESDAY, 15 SEPTEMBER 2026 — the header, which is upper-cased by CSS but
     written in title case, so it arrives here the same way. */
  { rx: new RegExp('^' + DL + ', (\\d{1,2}) ' + ML + ' (\\d{4})$'),
    to: function (m) { return m[2] + ' ' + MON_LONG[m[3]] + ' ' + m[4] + ' ' + DOW_LONG[m[1]]; } },

  /* Mon — 0  ->  Pzt — 0 */
  { rx: new RegExp('^' + D + ' — (.+)$'),
    to: function (m) { return DOW[m[1]] + ' — ' + m[2]; } },

  /* September 2026  ->  Eylül 2026 */
  { rx: new RegExp('^' + ML + ' (\\d{4})$'),
    to: function (m) { return MON_LONG[m[1]] + ' ' + m[2]; } },

  /* Sep 2026  ->  Eyl 2026 */
  { rx: new RegExp('^' + M + ' (\\d{4})$'),
    to: function (m) { return MON[m[1]] + ' ' + m[2]; } },

  /* 2026-09-02 — no log  ->  02.09.2026 — kayıt yok */
  { rx: /^(\d{4})-(\d{2})-(\d{2}) — (.+)$/,
    to: function (m) {
      var tail = { 'no log': 'kayıt yok' }[m[4]] || m[4];
      return m[3] + '.' + m[2] + '.' + m[1] + ' — ' + tail;
    } },

  /* Tue, 15 Sep 2026 · week 38  ->  15 Eyl 2026 Sal · 38. hafta */
  { rx: new RegExp('^' + D + ', (\\d{1,2}) ' + M + ' (\\d{4}) · week (\\d+)$'),
    to: function (m) { return m[2] + ' ' + MON[m[3]] + ' ' + m[4] + ' ' + DOW[m[1]] + ' · ' + m[5] + '. hafta'; } },

  /* Mon 14 Sep → Sun 20 Sep — the week range above the compass. */
  { rx: new RegExp('^' + D + ' (\\d{1,2}) ' + M + ' → ' + D + ' (\\d{1,2}) ' + M + '$'),
    to: function (m) {
      return m[2] + ' ' + MON[m[3]] + ' ' + DOW[m[1]] + ' → ' + m[5] + ' ' + MON[m[6]] + ' ' + DOW[m[4]];
    } }
];

FlowI18n.add('tr', { name: 'Turkish', native: 'Türkçe', locale: 'tr-TR' }, {
/* DICT-START */
  "— · 7-day average": "— · 7 günlük ortalama",
  "— · avg hours (7d)": "— · ort. saat (7g)",
  "— · best night": "— · en iyi gece",
  "— · most time spent on": "— · en çok zaman ayrılan",
  "— click to toggle done": "— bitti işaretini değiştirmek için tıkla",
  "— double-click it, pick which calendar to put it in. It syncs to your other devices through iCloud.": "— çift tıkla, hangi takvime koyacağını seç. iCloud üzerinden diğer cihazlarına eşitlenir.",
  "— open": "— aç",
  ", then Settings → Import & export → Import, and pick the file.": ", sonra Ayarlar → İçe ve dışa aktar → İçe aktar, ve dosyayı seç.",
  "…(truncated)": "…(kısaltıldı)",
  "…and {} more.": "…ve {} tane daha.",
  "…watch your life change": "…hayatının değişmesini izle",
  "· {} of {} on target": "· {2} hedeften {1} tutturuldu",
  "(1–3 per role — schedule them first, everything else fits around them)": "(rol başına 1–3 tane — önce onları planla, kalan her şey etraflarına oturur)",
  "(from {})": "({} kaynağından)",
  "(Habit 2 — your deepest values; everything below serves this)": "(2. Alışkanlık — en derin değerlerin; aşağıdaki her şey buna hizmet eder)",
  "(no answer)": "(cevap yok)",
  "(no data yet)": "(henüz veri yok)",
  "(the checklist and week plan adapt to the days you train)": "(kontrol listesi ve hafta planı antrenman günlerine göre uyarlanır)",
  "). Until those exist, CSV import is the working path and it costs nothing.": "). Onlar olmadan CSV içe aktarma çalışan yoldur ve hiçbir maliyeti yoktur.",
  "{} · {} journal entries": "{} · {} günlük kaydı",
  "{} · notes": "{} · notlar",
  "{} {}s in a row": "üst üste {} {}",
  "{} → {} · {} days of your own record.": "{} → {} · kendi kaydının {} günü.",
  "{} entries exported as Markdown ✓": "{} kayıt Markdown olarak dışa aktarıldı ✓",
  "{} events exported. Open the file to add them to Calendar.": "{} etkinlik dışa aktarıldı. Takvime eklemek için dosyayı aç.",
  "{} expense{} · {} total": "{} harcama{} · toplam {}",
  "{} expenses · {} total": "{} harcama · toplam {}",
  "{} of {} on target": "{2} hedeften {1} tutturuldu",
  "{} principle": "{} ilke",
  "{} principles": "{} ilke",
  "{} recovery codes left, made {}. Making new ones cancels the old.": "{2} tarihinde oluşturulan {1} kurtarma kodu kaldı. Yeni oluşturmak eskileri iptal eder.",
  "{} reminders exported — open the file on your iPhone": "{} hatırlatıcı dışa aktarıldı — dosyayı iPhone'unda aç",
  "{} rows ready · {}{}": "{} satır hazır · {}{}",
  "{} still to decide.": "{} tanesi hâlâ karar bekliyor.",
  "{} this month": "bu ay {}",
  "{} urgent + important{}": "{} acil + önemli{}",
  "{}{}. Your data is private to this account — nobody else signed in here can see it.": "{}{}. Verilerin bu hesaba özel — burada oturum açan başka kimse göremez.",
  "{}% overall": "genel %{}",
  "% of budget used": "bütçenin kullanılan yüzdesi",
  "% overall": "genel %",
  "← Prev": "← Önceki",
  "← To Do": "← Yapılacak",
  "→ level": "→ sabit",
  "→ Rock": "→ Kaya",
  "↑ Restore from backup": "↑ Yedekten geri yükle",
  "↑ rising": "↑ yükseliyor",
  "↓ .ics": "↓ .ics",
  "↓ Backup JSON": "↓ JSON yedeği",
  "↓ Download full backup": "↓ Tam yedeği indir",
  "↓ Export CSV": "↓ CSV dışa aktar",
  "↓ fading": "↓ zayıflıyor",
  "↓ JSON": "↓ JSON",
  "↓ Markdown": "↓ Markdown",
  "↩️ Big rock reopened:": "↩️ Büyük kaya yeniden açıldı:",
  "↩️ Session unmarked:": "↩️ Seans işareti kaldırıldı:",
  "↻ Refresh": "↻ Yenile",
  "+ Add bracket section": "+ Parantez bölümü ekle",
  "+ Add expense": "+ Harcama ekle",
  "+ Add habit": "+ Alışkanlık ekle",
  "+ Add line": "+ Satır ekle",
  "+ Add rock": "+ Kaya ekle",
  "+ Add task": "+ Görev ekle",
  "+ Section below": "+ Aşağıya bölüm",
  "+ Sub-section": "+ Alt bölüm",
  "+{} more": "+{} daha",
  "⌘/Ctrl + Enter saves. Drafts are kept if you navigate away mid-sentence.": "⌘/Ctrl + Enter kaydeder. Cümlenin ortasında ayrılırsan taslak korunur.",
  "⏱️ Time": "⏱️ Zaman",
  "⏱️ Time Tracker": "⏱️ Zaman Takibi",
  "⏱ Today": "⏱ Bugün",
  "▸ Details": "▸ Ayrıntılar",
  "▾ Close": "▾ Kapat",
  "◻️ Planned, not ticked": "◻️ Planlandı, işaretlenmedi",
  "⚙️ Settings": "⚙️ Ayarlar",
  "⚙ Settings": "⚙ Ayarlar",
  "⚠️ {}{} · gram gold is derived from the ounce price": "⚠️ {}{} · gram altın, ons fiyatından türetilir",
  "⚠ needs rescheduling": "⚠ yeniden planlanmalı",
  "⚠ Over budget by {}": "⚠ Bütçe {} aşıldı",
  "⚠️ overdue ·": "⚠️ gecikmiş ·",
  "⚠️ This browser is blocking local storage, so entries cannot be saved here. Open this file in Chrome, or export a backup regularly from the 📓 Journal tab.": "⚠️ Bu tarayıcı yerel depolamayı engelliyor, bu yüzden kayıtlar burada saklanamaz. Bu dosyayı Chrome'da aç ya da 📓 Günlük sekmesinden düzenli olarak yedek al.",
  "⚡ WHOOP": "⚡ WHOOP",
  "⚪ Connecting…": "⚪ Bağlanıyor…",
  "⚪ Low": "⚪ Düşük",
  "⚪ Offline · retrying": "⚪ Çevrimdışı · yeniden deneniyor",
  "✅ Big rock done:": "✅ Büyük kaya bitti:",
  "✅ Done": "✅ Bitti",
  "✅ Habit Tracker": "✅ Alışkanlık Takibi",
  "✅ Habits": "✅ Alışkanlıklar",
  "✅ Logged for today.": "✅ Bugün için kaydedildi.",
  "✅ Session done:": "✅ Seans bitti:",
  "✍️ Write": "✍️ Yaz",
  "✍️ Write my meal plan": "✍️ Beslenme planımı yaz",
  "✎ Manual": "✎ Elle",
  "✏️ Edit": "✏️ Düzenle",
  "✏️ Edit goal": "✏️ Hedefi düzenle",
  "✏️ Edit lines": "✏️ Satırları düzenle",
  "✏️ Edit note": "✏️ Notu düzenle",
  "✏️ Edit plan": "✏️ Planı düzenle",
  "✏️ Edit this day": "✏️ Bu günü düzenle",
  "✏️ Type your own…": "✏️ Kendin yaz…",
  "✓ added": "✓ eklendi",
  "✓ Done": "✓ Bitti",
  "✓ Save": "✓ Kaydet",
  "✓ Save note": "✓ Notu kaydet",
  "✓ saved": "✓ kaydedildi",
  "✓ Saved": "✓ Kaydedildi",
  "✓ today is written": "✓ bugün yazıldı",
  "❤️ Social — real time with people, phone away": "❤️ Sosyal — insanlarla gerçek zaman, telefon uzakta",
  "➕ Add an expense by hand": "➕ Elle harcama ekle",
  "➕ New habit: {}": "➕ Yeni alışkanlık: {}",
  "⬇️ Download calendar file": "⬇️ Takvim dosyasını indir",
  "⭐ North Star": "⭐ Kuzey Yıldızı",
  "🌱 Q2 — Not Urgent & Important": "🌱 Q2 — Acil Değil ve Önemli",
  "🍗 Nutrition & Recovery": "🍗 Beslenme ve Toparlanma",
  "🍳 Breakfast": "🍳 Kahvaltı",
  "🍽️ Dinner": "🍽️ Akşam yemeği",
  "🍽️ Meals & diet": "🍽️ Öğünler ve beslenme",
  "🎉 Q4 — Not Urgent & Not Important": "🎉 Q4 — Acil Değil ve Önemli Değil",
  "🎧 Spiritual — something creative ×3": "🎧 Ruhsal — yaratıcı bir şey ×3",
  "🎨 Appearance": "🎨 Görünüm",
  "🎯 North-Star Goal": "🎯 Kuzey Yıldızı Hedefi",
  "🎯 Priorities": "🎯 Öncelikler",
  "🎯 Priorities — Importance × Urgency": "🎯 Öncelikler — Önem × Aciliyet",
  "🏋️ Conditioning or a long walk": "🏋️ Kondisyon ya da uzun yürüyüş",
  "🏋️ Legs": "🏋️ Bacak",
  "🏋️ Pull — Back and Biceps": "🏋️ Çekiş — Sırt ve Biseps",
  "🏋️ Push — Chest, Shoulders, Triceps": "🏋️ İtiş — Göğüs, Omuz, Triseps",
  "🏋️ Training": "🏋️ Antrenman",
  "🏋️ Training session": "🏋️ Antrenman seansı",
  "🏋️ Training sessions": "🏋️ Antrenman seansları",
  "🏋️ Upper Body": "🏋️ Üst Vücut",
  "🏢 Work": "🏢 İş",
  "🏦 Bank & statements": "🏦 Banka ve ekstreler",
  "🏦 Import a bank statement": "🏦 Banka ekstresi içe aktar",
  "🏷 Categories": "🏷 Kategoriler",
  "👤 Account": "👤 Hesap",
  "👤 You": "👤 Sen",
  "💡 Brainstorm — Business Fundamentals": "💡 Beyin Fırtınası — İşin Temelleri",
  "💧 2–3 litres of water": "💧 2–3 litre su",
  "💪 Physical — train 4× this week": "💪 Fiziksel — bu hafta 4× antrenman",
  "💬 Ask": "💬 Sor",
  "💰 {} spending": "💰 {} harcaması",
  "💰 Finances": "💰 Finans",
  "💰 Money": "💰 Para",
  "💾 Backup": "💾 Yedek",
  "💾 Data": "💾 Veri",
  "💾 Export backup (JSON)": "💾 Yedeği dışa aktar (JSON)",
  "💾 Save notes": "💾 Notları kaydet",
  "📅 Put this in your calendar": "📅 Bunu takvimine koy",
  "📅 Rest of the week": "📅 Haftanın kalanı",
  "📅 Send flagged → Calendar": "📅 İşaretlileri gönder → Takvim",
  "📅 Today": "📅 Bugün",
  "📆 Google Calendar": "📆 Google Takvim",
  "📆 Or write straight into Google Calendar": "📆 Ya da doğrudan Google Takvim'e yaz",
  "📊 Live roll-up": "📊 Canlı toplam",
  "📊 Visuals": "📊 Görseller",
  "📋 Copy plan → next week": "📋 Planı kopyala → gelecek hafta",
  "📋 Hide activity log": "📋 Etkinlik kaydını gizle",
  "📋 Program": "📋 Program",
  "📋 Show activity log": "📋 Etkinlik kaydını göster",
  "📋 To Do": "📋 Yapılacak",
  "📌 Scheduled tasks": "📌 Planlı görevler",
  "📓 Journal": "📓 Günlük",
  "📓 Journal — every entry, saved forever": "📓 Günlük — her kayıt, sonsuza dek saklı",
  "📓 Today isn't written yet": "📓 Bugün henüz yazılmadı",
  "📚 Mental — read or study ×3": "📚 Zihinsel — oku ya da çalış ×3",
  "📝 {} notes updated": "📝 {} not güncellendi",
  "📝 note": "📝 not",
  "📝 Notes & running log": "📝 Notlar ve akan kayıt",
  "📝 Notes for {}": "📝 {} notları",
  "📝 Optional note or details — who's there, what's still pending (e.g. flight ticket still needs to be bought)…": "📝 İsteğe bağlı not ya da ayrıntı — kim var, ne bekliyor (ör. uçak bileti hâlâ alınmadı)…",
  "📝 Task notes": "📝 Görev notları",
  "📝 Weekly review (Sunday)": "📝 Haftalık gözden geçirme (Pazar)",
  "📞 Q3 — Urgent & Not Important": "📞 Q3 — Acil ve Önemli Değil",
  "📤 Send this to your calendar": "📤 Bunu takvimine gönder",
  "📤 Share this": "📤 Bunu paylaş",
  "📥 Import backup": "📥 Yedek içe aktar",
  "📥 Restore": "📥 Geri yükle",
  "📥 Shared with you": "📥 Seninle paylaşılan",
  "📥 Shared with you{}": "📥 Seninle paylaşılan{}",
  "📧 Email": "📧 E-posta",
  "📸 Snap a receipt": "📸 Fiş çek",
  "🔍 Problem I'm Solving": "🔍 Çözdüğüm Problem",
  "🔎 Routine audit — kept {}, changed {}, cut {}": "🔎 Rutin denetimi — {} korundu, {} değişti, {} kesildi",
  "🔒 Not signed in": "🔒 Oturum açılmadı",
  "🔔 iOS Reminders": "🔔 iOS Hatırlatıcılar",
  "🔔 Send flagged → Reminders": "🔔 İşaretlileri gönder → Hatırlatıcılar",
  "🔔 To reminders": "🔔 Hatırlatıcılara",
  "🔗 Copy link": "🔗 Bağlantıyı kopyala",
  "🔗 Links": "🔗 Bağlantılar",
  "🔥 Q1 — Urgent & Important": "🔥 Q1 — Acil ve Önemli",
  "🔴 High": "🔴 Yüksek",
  "🕘 time": "🕘 saat",
  "🕘 Time chips": "🕘 Zaman etiketleri",
  "🗒️ Week plan written ({})": "🗒️ Hafta planı yazıldı ({})",
  "🗣️ Study Languages — open LinguaCoach": "🗣️ Dil Çalış — LinguaCoach'u aç",
  "🤖 Connect to Claude": "🤖 Claude'a bağlan",
  "🤝 Shared tasks": "🤝 Paylaşılan görevler",
  "🤝 Social — reach out to someone who matters": "🤝 Sosyal — senin için önemli birine ulaş",
  "🥗 Diet": "🥗 Beslenme",
  "🥗 Lunch": "🥗 Öğle yemeği",
  "🥗 Physical — eat to plan most days": "🥗 Fiziksel — çoğu gün plana göre beslen",
  "🥤 Post-workout protein": "🥤 Antrenman sonrası protein",
  "🧠 Brainstorm": "🧠 Beyin Fırtınası",
  "🧠 Mental — learn one new thing": "🧠 Zihinsel — yeni bir şey öğren",
  "🧠 Mood": "🧠 Ruh hali",
  "🧠 Mood {}/5 · Energy {}/5{}": "🧠 Ruh hali {}/5 · Enerji {}/5{}",
  "🧠 Mood & Energy": "🧠 Ruh Hali ve Enerji",
  "🧩 Make it yours": "🧩 Kendine göre ayarla",
  "🧭 Planning": "🧭 Planlama",
  "🧭 Week Compass": "🧭 Hafta Pusulası",
  "🪒 Blade line added: {}": "🪒 Balta satırı eklendi: {}",
  "🪒 Blade line removed: {}": "🪒 Balta satırı kaldırıldı: {}",
  "🪒 Blade line renamed: {}": "🪒 Balta satırı yeniden adlandırıldı: {}",
  "🪒 Sharpen the Blade — this week": "🪒 Baltayı Bile — bu hafta",
  "🪒 Sharpen the Blade: {}": "🪒 Baltayı Bile: {}",
  "🪒 Sharpen the Blade: {} ({})": "🪒 Baltayı Bile: {} ({})",
  "🪧 Mission statement updated": "🪧 Misyon bildirisi güncellendi",
  "🪧 Personal Mission Statement": "🪧 Kişisel Misyon Bildirisi",
  "🪧 Spiritual — weekly review + mission check": "🪧 Ruhsal — haftalık gözden geçirme + misyon kontrolü",
  "🪨 Big rock added ({}): {}": "🪨 Büyük kaya eklendi ({}): {}",
  "🪨 Big rock done: {}": "🪨 Büyük kaya bitti: {}",
  "🪨 Big rock moved {} → {}: {}": "🪨 Büyük kaya taşındı {} → {}: {}",
  "🪨 Big Rocks": "🪨 Büyük Kayalar",
  "🪨 Big Rocks — week {}": "🪨 Büyük Kayalar — {}. hafta",
  "🪨 Big Rocks for this week": "🪨 Bu haftanın Büyük Kayaları",
  "😴 Sleep": "😴 Uyku",
  "😴 Sleep & Mood": "😴 Uyku ve Ruh Hali",
  "😴 Sleep, Recovery & Mood": "😴 Uyku, Toparlanma ve Ruh Hali",
  "🚀 Side Project": "🚀 Yan Proje",
  "🚧 In Progress": "🚧 Devam Ediyor",
  "🚫 No snacking between meals": "🚫 Öğün aralarında atıştırma yok",
  "🛋️ Rest day": "🛋️ Dinlenme günü",
  "🟠 {} change{} waiting to sync": "🟠 {} değişiklik{} eşitlenmeyi bekliyor",
  "🟡 Med": "🟡 Orta",
  "🟡 Medium": "🟡 Orta",
  "🟢 Database · {} · {} sets": "🟢 Veritabanı · {} · {} set",
  "🟢 Database{}": "🟢 Veritabanı{}",
  "£0 · monthly income": "£0 · aylık gelir",
  "£0.00 · spent this month": "£0.00 · bu ay harcanan",
  "0 · best current streak": "0 · en iyi güncel seri",
  "0 · done today": "0 · bugün biten",
  "0 · entries today": "0 · bugünkü kayıt",
  "0 · in progress": "0 · devam eden",
  "0 · open tasks": "0 · açık görev",
  "0 · total entries": "0 · toplam kayıt",
  "0 characters": "0 karakter",
  "0/0 · big rocks done (this week)": "0/0 · biten büyük kaya (bu hafta)",
  "0/5 · sessions this week": "0/5 · bu haftaki seans",
  "0% · today's compliance": "0% · bugünkü uyum",
  "0% · week completion": "0% · hafta tamamlanma",
  "0min": "0dk",
  "0min · logged this week": "0dk · bu hafta kaydedilen",
  "1 · .ics file — works now": "1 · .ics dosyası — şimdi çalışır",
  "1 · open q2 priorities": "1 · açık q2 önceliği",
  "1 day before": "1 gün önce",
  "1 h": "1 sa",
  "1 hour before": "1 saat önce",
  "1 section": "1 bölüm",
  "1.5 h": "1,5 sa",
  "10 recovery codes left, made {}. Making new ones cancels the old.": "{} tarihinde oluşturulan 10 kurtarma kodu kaldı. Yeni oluşturmak eskileri iptal eder.",
  "12 weeks": "12 hafta",
  "15 min": "15 dk",
  "15 min before": "15 dk önce",
  "2 · Apple Shortcut — automatic": "2 · Apple Kısayolu — otomatik",
  "2 h": "2 sa",
  "2 open": "2 açık",
  "2 weeks": "2 hafta",
  "3 · CalDAV to iCloud — hands-off": "3 · iCloud'a CalDAV — elini sürmeden",
  "3 h": "3 sa",
  "3 of 28 across every tab": "her sekmede 28 içinden 3",
  "3-Month Roadmap": "3 Aylık Yol Haritası",
  "30 min": "30 dk",
  "30 min before": "30 dk önce",
  "4 h": "4 sa",
  "4 weeks": "4 hafta",
  "4–5 good": "4–5 iyi",
  "45 min": "45 dk",
  "5 min before": "5 dk önce",
  "7-day average": "7 günlük ortalama",
  "7–9 h sleep last night": "Dün gece 7–9 sa uyku",
  "7–9h target": "7–9 sa hedef",
  "70% of our life is things we do everyday": "Hayatımızın %70'i her gün yaptığımız şeylerdir",
  "8 h": "8 sa",
  "8 weeks": "8 hafta",
  "a day": "bir gün",
  "a month": "bir ay",
  "A note is saved without leaving this screen.": "Bir not, bu ekrandan çıkmadan kaydedilir.",
  "A token is as good as your password for reading and adding — treat it like one. If you no longer recognise a token in the list, revoke it; anything using it stops working immediately and nothing you have saved is touched.": "Bir anahtar, okuma ve ekleme için parolan kadar güçlüdür — ona göre davran. Listedeki bir anahtarı artık tanımıyorsan iptal et; onu kullanan her şey anında çalışmayı bırakır ve kaydettiğin hiçbir şeye dokunulmaz.",
  "a week": "bir hafta",
  "Accept": "Kabul et",
  "Access tokens": "Erişim anahtarları",
  "across every entry": "her kayıtta",
  "Action items: {}": "Aksiyon maddeleri: {}",
  "Add": "Ekle",
  "Add a comment…": "Yorum ekle…",
  "Add a focus area…": "Odak alanı ekle…",
  "Add a habit (e.g. Read 20 min, Cold shower, Meditate)...": "Alışkanlık ekle (ör. 20 dk oku, Soğuk duş, Meditasyon)...",
  "Add a line — e.g. 🎧 Craft — one finished idea": "Satır ekle — ör. 🎧 Zanaat — bitmiş bir fikir",
  "Add a principle…": "İlke ekle…",
  "Add a task for {}…": "{} için görev ekle…",
  "Add action item or idea… (Enter)": "Aksiyon maddesi ya da fikir ekle… (Enter)",
  "Add birth date": "Doğum tarihi ekle",
  "Add expense": "Harcama ekle",
  "Add New Reminder": "Yeni Hatırlatıcı Ekle",
  "Add something for today…": "Bugüne bir şey ekle…",
  "Add something to today…": "Bugüne bir şey ekle…",
  "Add to my priorities": "Önceliklerime ekle",
  "Add to week": "Haftaya ekle",
  "Add workout": "Antrenman ekle",
  "Add your Google OAuth Client ID in Settings → Integrations first.": "Önce Ayarlar → Entegrasyonlar'da Google OAuth İstemci Kimliğini ekle.",
  "Add...": "Ekle...",
  "Added to ": "Şuraya eklendi: ",
  "Added to today ✓": "Bugüne eklendi ✓",
  "Adds the Reminders buttons to the Planner tab and note sections.": "Planlayıcı sekmesine ve not bölümlerine Hatırlatıcılar düğmelerini ekler.",
  "Aggregator": "Toplayıcı",
  "Aggressive / cut (2.2 g/kg)": "Agresif / kesim (2,2 g/kg)",
  "Alert": "Uyarı",
  "All": "Hepsi",
  "all clear": "her şey yolunda",
  "all done": "hepsi bitti",
  "All sections": "Tüm bölümler",
  "All time": "Tüm zamanlar",
  "already done": "zaten bitti",
  "Am I keeping up with training?": "Antrenmana devam edebiliyor muyum?",
  "Amount": "Tutar",
  "Amount (£)": "Tutar (£)",
  "An access token below is the manual way in, for a client that cannot do the above, or for your own scripts.": "Aşağıdaki erişim anahtarı elle giriş yoludur: yukarıdakini yapamayan bir istemci ya da kendi betiklerin için.",
  "An account with that email already exists.": "Bu e-postayla bir hesap zaten var.",
  "and connect your WHOOP account. Setup guide included.": "ve WHOOP hesabını bağla. Kurulum rehberi dahildir.",
  "Another date…": "Başka bir tarih…",
  "Anthropic is rate-limiting this key. Try again shortly.": "Anthropic bu anahtarı hız sınırına takıyor. Birazdan tekrar dene.",
  "Anything you gave a date and a time — Planner rows and items time-blocked from any tab": "Tarih ve saat verdiğin her şey — Planlayıcı satırları ve herhangi bir sekmeden zaman bloğuna alınan maddeler",
  "Appearance": "Görünüm",
  "Apple Calendar": "Apple Takvim",
  "Apple Calendar (.ics)": "Apple Takvim (.ics)",
  "Apple downloads a standard .ics you open on your Mac or iPhone. Google writes straight into your calendar and updates the same events on every later export instead of duplicating them.": "Apple, Mac'inde ya da iPhone'unda açacağın standart bir .ics indirir. Google doğrudan takvimine yazar ve sonraki her aktarımda aynı etkinlikleri kopyalamak yerine günceller.",
  "Apple gives no public web API for Reminders, so there are three real routes. The first works immediately; the second is the one worth setting up once.": "Apple, Hatırlatıcılar için herkese açık bir web API'si vermiyor; bu yüzden üç gerçek yol var. İlki hemen çalışır, ikincisi bir kez kurmaya değer olanıdır.",
  "Apply": "Uygula",
  "Apr": "Nis",
  "Aquarius": "Kova",
  "Aries": "Koç",
  "Ask": "Sor",
  "Ask about your own record": "Kendi kaydın hakkında sor",
  "Ask about your week…": "Haftan hakkında sor…",
  "Ask it \"what's on my week?\" to check it worked.": "Çalıştığını görmek için ona \"haftamda ne var?\" diye sor.",
  "Ask whoever shared The Flow with you for the invite code.": "The Flow'u seninle paylaşan kişiden davet kodunu iste.",
  "At least 10 characters": "En az 10 karakter",
  "at the time": "o saatte",
  "Athlete": "Sporcu",
  "Audit done — kept {}, changed {}, cut {}": "Denetim bitti — {} korundu, {} değişti, {} kesildi",
  "Audit in progress": "Denetim sürüyor",
  "audit your routine every 6 months": "rutinini 6 ayda bir denetle",
  "Aug": "Ağu",
  "Authorised JavaScript origins:": "Yetkili JavaScript kaynakları:",
  "Auto / day-first (TR, EU)": "Otomatik / önce gün (TR, AB)",
  "Auto-sync: run": "Otomatik eşitleme: çalıştır",
  "Automation → run daily at 06:00": "Otomasyon → her gün 06:00'da çalıştır",
  "Avg energy (7d)": "Ort. enerji (7g)",
  "Avg hours (7d)": "Ort. saat (7g)",
  "Avg mood (7d)": "Ort. ruh hali (7g)",
  "Back": "Geri",
  "Back to signing in": "Oturum açmaya dön",
  "Back to this week": "Bu haftaya dön",
  "Backup": "Yedek",
  "Backup restored ✓": "Yedek geri yüklendi ✓",
  "barely happened": "neredeyse hiç olmadı",
  "Bars": "Çubuklar",
  "Bedtime": "Yatma saati",
  "Before": "Önce",
  "Best current streak": "En iyi güncel seri",
  "Best day this week": "Bu haftanın en iyi günü",
  "Best night": "En iyi gece",
  "Big Rocks · {} of {}": "Büyük Kayalar · {} / {}",
  "Big rocks done (this week)": "Biten büyük kayalar (bu hafta)",
  "Birth date": "Doğum tarihi",
  "Bitcoin": "Bitcoin",
  "Blocked": "Engellendi",
  "Body": "Beden",
  "Body weight log (kg)": "Vücut ağırlığı kaydı (kg)",
  "Bodyweight (kg)": "Vücut ağırlığı (kg)",
  "Brainstorm": "Beyin Fırtınası",
  "Brand Identity": "Marka Kimliği",
  "Breakdown": "Dağılım",
  "Budget": "Bütçe",
  "budget (£)": "bütçe (£)",
  "Budget setup —": "Bütçe kurulumu —",
  "Build muscle (1.8 g/kg)": "Kas yap (1,8 g/kg)",
  "Build muscle + lean (2.0 g/kg)": "Kas yap + yağ yak (2,0 g/kg)",
  "Build this once, then run it from the Home Screen or on a schedule:": "Bunu bir kez kur, sonra Ana Ekrandan ya da bir zamanlamayla çalıştır:",
  "Business": "İş",
  "CalDAV push failed (HTTP {})": "CalDAV gönderimi başarısız (HTTP {})",
  "CalDAV: {} pushed, {} failed": "CalDAV: {} gönderildi, {} başarısız",
  "Calendar ID": "Takvim kimliği",
  "Cancel": "Vazgeç",
  "Cancer": "Yengeç",
  "Cannot reach the server right now. Your edits are safe on this device and will sync automatically — tap to try now.": "Sunucuya şu anda ulaşılamıyor. Değişikliklerin bu cihazda güvende ve kendiliğinden eşitlenecek — şimdi denemek için dokun.",
  "Capricorn": "Oğlak",
  "Capture": "Yakala",
  "Cardio": "Kardiyo",
  "Carry on": "Devam et",
  "Category": "Kategori",
  "Category updated — that merchant is remembered.": "Kategori güncellendi — o satıcı artık hatırlanıyor.",
  "Change": "Değiştir",
  "Change password": "Parolayı değiştir",
  "Check the amount before saving.": "Kaydetmeden önce tutarı kontrol et.",
  "Check-in": "Yoklama",
  "Checkboxes ticked": "İşaretlenen kutular",
  "Checking sync…": "Eşitleme kontrol ediliyor…",
  "Checking your recovery codes…": "Kurtarma kodların kontrol ediliyor…",
  "Choosing an aggregator here only records the intent — the actual pull runs server-side and needs API keys as environment variables (": "Burada bir toplayıcı seçmek yalnızca niyeti kaydeder — asıl çekme işlemi sunucuda çalışır ve ortam değişkeni olarak API anahtarları ister (",
  "Clear": "Temizle",
  "Click to edit": "Düzenlemek için tıkla",
  "Click to toggle done": "Bitti işaretini değiştirmek için tıkla",
  "Close": "Kapat",
  "Cloud save didn’t finish": "Buluta kaydetme tamamlanmadı",
  "Code {} copied — send it to one person.": "{} kodu kopyalandı — tek bir kişiye gönder.",
  "Code cancelled.": "Kod iptal edildi.",
  "Collapse / expand": "Daralt / genişlet",
  "Comment": "Yorum",
  "Commute": "Yol",
  "Completion": "Tamamlanma",
  "Compressing the photo…": "Fotoğraf sıkıştırılıyor…",
  "Conditioning": "Kondisyon",
  "Conditioning or a long walk": "Kondisyon ya da uzun yürüyüş",
  "Connected apps": "Bağlı uygulamalar",
  "connected through sign-in": "oturum açarak bağlandı",
  "Connection": "Bağlantı",
  "consecutive days with an entry": "kayıt girilen ardışık gün",
  "context, link, location…": "bağlam, bağlantı, konum…",
  "Copied": "Kopyalandı",
  "Copied ✓": "Kopyalandı ✓",
  "Copied.": "Kopyalandı.",
  "Copy": "Kopyala",
  "Copy the full plan of the week you are viewing into next week, then jump there to adjust it": "Baktığın haftanın tüm planını gelecek haftaya kopyala, sonra oraya geçip düzenle",
  "Could not load Google sign-in": "Google oturum açma yüklenemedi",
  "Could not load the OCR engine (offline?)": "OCR motoru yüklenemedi (çevrimdışı mısın?)",
  "Could not open that shared task.": "Paylaşılan görev açılamadı.",
  "Could not reach Google just now.": "Şu anda Google'a ulaşılamadı.",
  "Could not reach the assistant.": "Asistana ulaşılamadı.",
  "Could not reach the server.": "Sunucuya ulaşılamadı.",
  "Could not reach the server. Try again in a moment.": "Sunucuya ulaşılamadı. Birazdan tekrar dene.",
  "Could not reach your priorities.": "Önceliklerine ulaşılamadı.",
  "Could not read that file": "Bu dosya okunamadı",
  "Could not read that image: {}": "Bu görsel okunamadı: {}",
  "Could not read your access tokens just now.": "Erişim anahtarların şu anda okunamadı.",
  "Could not save that.": "Bu kaydedilemedi.",
  "Could not share that.": "Bu paylaşılamadı.",
  "Could not start the download — copy them instead.": "İndirme başlatılamadı — bunun yerine kopyala.",
  "Couldn’t read that file": "Bu dosya okunamadı",
  "Create access token": "Erişim anahtarı oluştur",
  "Create account": "Hesap oluştur",
  "Create an account instead": "Bunun yerine hesap oluştur",
  "Create your account": "Hesabını oluştur",
  "Create your account and your work will be carried over.": "Hesabını oluştur, yaptıkların taşınsın.",
  "Creating your account…": "Hesabın oluşturuluyor…",
  "Creative": "Yaratıcı",
  "Credentials → Create →": "Kimlik bilgileri → Oluştur →",
  "Currency": "Para birimi",
  "Currently upgraded: {} card{} on this page.": "Şu anda yükseltilmiş: bu sayfada {} kart{}.",
  "Currently upgraded: 1 card on this page.": "Şu anda yükseltilmiş: bu sayfada 1 kart.",
  "Custom Profile": "Özel Profil",
  "Cut": "Kesildi",
  "Daily checklist — one per line": "Günlük kontrol listesi — her satıra bir madde",
  "Daily recovery checklist": "Günlük toparlanma listesi",
  "Daily summary": "Günlük özet",
  "Daily target:": "Günlük hedef:",
  "Date": "Tarih",
  "Day | Title | Time": "Gün | Başlık | Saat",
  "Day Strain": "Gün Zorlanması",
  "Day streak": "Gün serisi",
  "Days logged in a row": "Üst üste kaydedilen gün",
  "Days with entries": "Kayıt girilen günler",
  "Dec": "Ara",
  "Default duration (min)": "Varsayılan süre (dk)",
  "Default shape": "Varsayılan biçim",
  "Delete": "Sil",
  "Delete \"{}\" and everything inside it?": "\"{}\" ve içindeki her şey silinsin mi?",
  "Delete my account and everything in it": "Hesabımı ve içindeki her şeyi sil",
  "Delete section": "Bölümü sil",
  "Delete the entry from {}? This cannot be undone.": "{} tarihli kayıt silinsin mi? Bu geri alınamaz.",
  "Delete this account": "Bu hesabı sil",
  "Delete this task": "Bu görevi sil",
  "Deleted": "Silindi",
  "Description": "Açıklama",
  "Details / notes…": "Ayrıntılar / notlar…",
  "Diet": "Beslenme",
  "Diet checklist": "Beslenme listesi",
  "Diet compliance (7d)": "Beslenme uyumu (7g)",
  "Diet, expand": "Beslenme, genişlet",
  "Dining": "Yeme içme",
  "Direction": "Yön",
  "Discard": "Vazgeç",
  "Disconnect": "Bağlantıyı kes",
  "Disconnect {}? It stops reaching your Flow straight away. Nothing you have saved is affected.": "{} bağlantısı kesilsin mi? Flow'una erişimi anında durur. Kaydettiğin hiçbir şey etkilenmez.",
  "Disconnected ✓": "Bağlantı kesildi ✓",
  "Dismiss": "Kapat",
  "Display name": "Görünen ad",
  "Do": "Yap",
  "DO first — necessity": "ÖNCE yap — zorunluluk",
  "Do these": "Bunları yap",
  "Dollar": "Dolar",
  "Done": "Bitti",
  "Done ✓": "Bitti ✓",
  "Done this week": "Bu hafta biten",
  "Done today": "Bugün biten",
  "Download": "İndir",
  "Download a backup of ALL data & logs": "TÜM verilerin ve kayıtların yedeğini indir",
  "Download this section as a calendar event with an alarm": "Bu bölümü uyarılı bir takvim etkinliği olarak indir",
  "Download this section as an iOS reminder with an alarm": "Bu bölümü uyarılı bir iOS hatırlatıcısı olarak indir",
  "Drag to reorder": "Sıralamak için sürükle",
  "Drink ~3 L water": "~3 L su iç",
  "Drop a CSV here, or tap to choose one": "Buraya bir CSV bırak ya da seçmek için dokun",
  "due now": "şimdi gerekiyor",
  "Due: {}": "Bitiş: {}",
  "Duration": "Süre",
  "e.g. woke up once, vivid dreams...": "ör. bir kez uyandım, canlı rüyalar...",
  "EARNED rewards — after the rocks are placed": "HAK EDİLEN ödüller — kayalar yerleştikten sonra",
  "Eating Out": "Dışarıda Yemek",
  "Eating Out budget (£)": "Dışarıda yemek bütçesi (£)",
  "Edit": "Düzenle",
  "edit ›": "düzenle ›",
  "Edit lines": "Satırları düzenle",
  "Edit principle": "İlkeyi düzenle",
  "Edit this priority": "Bu önceliği düzenle",
  "Edit this task": "Bu görevi düzenle",
  "Edit what you plan to train this day": "Bu gün ne çalışmayı planladığını düzenle",
  "Education": "Eğitim",
  "Email": "E-posta",
  "Email me a link instead": "Bunun yerine bana bağlantı gönder",
  "Enable Reminders export": "Hatırlatıcı dışa aktarmayı aç",
  "Enable the": "Şunu aç:",
  "End time": "Bitiş saati",
  "End time (optional)": "Bitiş saati (isteğe bağlı)",
  "Energy": "Enerji",
  "energy {}/5": "enerji {}/5",
  "Enter a duration first.": "Önce bir süre gir.",
  "Enter bodyweight to set target.": "Hedefi belirlemek için vücut ağırlığını gir.",
  "Entertainment": "Eğlence",
  "Entertainment budget (£)": "Eğlence bütçesi (£)",
  "entrepreneur": "girişimci",
  "Entries": "Kayıtlar",
  "Entries this week": "Bu haftaki kayıtlar",
  "Entries today": "Bugünkü kayıtlar",
  "Entries written": "Yazılan kayıtlar",
  "Entry deleted": "Kayıt silindi",
  "Entry saved ✓": "Kayıt kaydedildi ✓",
  "Entry updated ✓": "Kayıt güncellendi ✓",
  "Erase everything the upgrade pack stores — schedules, expenses, receipts and notes? Your original Flow data is not touched.": "Yükseltme paketinin sakladığı her şey silinsin mi — planlar, harcamalar, fişler ve notlar? Asıl Flow verilerine dokunulmaz.",
  "Erase upgrade-pack data": "Yükseltme paketi verisini sil",
  "Errands": "İşler",
  "Euro": "Euro",
  "Every {} months": "Her {} ayda bir",
  "Every log from every tab lands here automatically, stamped with the date and time of entry, and is never deleted unless you delete it. Export a backup file any time; import it to restore or move to another browser.": "Her sekmedeki her kayıt, giriş tarihi ve saatiyle damgalanarak buraya kendiliğinden düşer ve sen silmedikçe asla silinmez. İstediğin zaman bir yedek dosyası dışa aktar; geri yüklemek ya da başka bir tarayıcıya taşımak için içe aktar.",
  "Everything": "Her şey",
  "Everything goes: your journal, tasks, money, training, the lot — along with every session, access token and assistant connection. It cannot be undone and there is no copy.": "Her şey gider: günlüğün, görevlerin, paran, antrenmanın, hepsi — her oturum, erişim anahtarı ve asistan bağlantısıyla birlikte. Geri alınamaz ve hiçbir kopyası yoktur.",
  "Everything saves automatically and lands in the 📓 Journal. Use ✏️ on any day to write what you plan to train; use ← → to plan and view upcoming weeks; 📋 copies a whole week's plan forward.": "Her şey kendiliğinden kaydedilir ve 📓 Günlük'e düşer. Herhangi bir günde ne çalışmayı planladığını yazmak için ✏️ kullan; gelecek haftaları planlamak ve görmek için ← →; 📋 bir haftanın tüm planını ileriye kopyalar.",
  "Everything that is not part of the daily loop.": "Günlük döngünün parçası olmayan her şey.",
  "Everything the upgrade pack stores lives under": "Yükseltme paketinin sakladığı her şey şurada durur:",
  "Everything you gave a time to, from any tab. Add times with the 🕘 chip that now sits on every task row.": "Herhangi bir sekmede saat verdiğin her şey. Saatleri, artık her görev satırında duran 🕘 etiketiyle ekle.",
  "Executive": "Yönetici",
  "Exercises": "Hareketler",
  "Expense": "Harcama",
  "Expenses this month": "Bu ayki harcamalar",
  "Export CSV from your internet banking, drop it here, and every line is dated, categorised and de-duplicated against what you already have. Re-importing an overlapping file is safe.": "İnternet bankacılığından CSV dışa aktar, buraya bırak; her satır tarihlenir, kategorilenir ve elindekilerle karşılaştırılıp yinelenenler ayıklanır. Örtüşen bir dosyayı yeniden içe aktarmak güvenlidir.",
  "Export reminders now": "Hatırlatıcıları şimdi dışa aktar",
  "Export, AirDrop or email the file to yourself, open it on the iPhone and choose Reminders. Each task carries its due date and alert.": "Dosyayı dışa aktar, AirDrop'la ya da kendine e-postayla gönder; iPhone'da aç ve Hatırlatıcılar'ı seç. Her görev kendi tarihini ve uyarısını taşır.",
  "exported — open the file to add it to your calendar.": "dışa aktarıldı — takvimine eklemek için dosyayı aç.",
  "Exports with an alarm to Apple Calendar, Google Calendar and iOS Reminders.": "Apple Takvim, Google Takvim ve iOS Hatırlatıcılar'a uyarıyla aktarır.",
  "Exports write directly into your Google calendar and are idempotent: the same task always maps to the same event, so re-exporting updates it instead of creating a duplicate.": "Dışa aktarma doğrudan Google takvimine yazar ve tekrara dayanıklıdır: aynı görev her zaman aynı etkinliğe karşılık gelir, yani yeniden aktarmak kopya oluşturmaz, günceller.",
  "Extra items on training days — one per line": "Antrenman günlerinde ek maddeler — her satıra bir tane",
  "Family & Friends": "Aile ve Arkadaşlar",
  "Feb": "Şub",
  "feminine": "dişil",
  "Filter": "Filtre",
  "Finances": "Finans",
  "Finish the audit": "Denetimi bitir",
  "Fitness": "Form",
  "Flag a section with 🔕 → 🔔 first.": "Önce bir bölümü 🔕 → 🔔 ile işaretle.",
  "flat": "düz",
  "Focus": "Odak",
  "Focus areas": "Odak alanları",
  "Focus areas, expand": "Odak alanları, genişlet",
  "Food & Groceries": "Yiyecek ve Market",
  "Food & Groceries budget (£)": "Yiyecek ve market bütçesi (£)",
  "for auto-sync):": "otomatik eşitleme için):",
  "Forget all": "Hepsini unut",
  "Forgot your password?": "Parolanı mı unuttun?",
  "Fri": "Cu",
  "Friday": "Cuma",
  "Friends": "Arkadaşlar",
  "Friends, expand": "Arkadaşlar, genişlet",
  "From": "Kimden",
  "From receipts you photograph and statements you import, in the Finances tab.": "Finans sekmesinde, fotoğrafladığın fişlerden ve içe aktardığın ekstrelerden.",
  "From The Flow · {}": "The Flow'dan · {}",
  "Fuel": "Yakıt",
  "Full log": "Tam kayıt",
  "g protein": "g protein",
  "Gemini": "İkizler",
  "Generate the app-specific password at appleid.apple.com → Sign-In and Security. Never put your real Apple password there.": "Uygulamaya özel parolayı appleid.apple.com → Oturum Açma ve Güvenlik bölümünden oluştur. Gerçek Apple parolanı oraya asla yazma.",
  "Get Contents of URL": "URL İçeriğini Al",
  "Get Dictionary Value": "Sözlük Değerini Al",
  "Get fit / improve health": "Forma gir / sağlığı iyileştir",
  "get rid of what isn't": "yaramayanı at",
  "Give Claude an access token and it can read your week, add Big Rocks, tick habits and reword your own lists — working on this account and no other. It can add and change things; removing anything stays something you do here.": "Claude'a bir erişim anahtarı ver; haftanı okuyabilir, Büyük Kaya ekleyebilir, alışkanlık işaretleyebilir ve kendi listelerini yeniden yazabilir — yalnızca bu hesapta, başka hiçbirinde. Ekleyip değiştirebilir; silmek her zaman senin burada yaptığın bir şey olarak kalır.",
  "Give your birth date and the daily read is written for your sign. Everything it claims still comes from your own record.": "Doğum tarihini ver, günlük okuma burcuna göre yazılsın. Söylediği her şey yine senin kendi kaydından gelir.",
  "Go to": "Git",
  "Go to a section, or start a note…": "Bir bölüme git ya da not yazmaya başla…",
  "Go-to-Market": "Pazara Giriş",
  "Goal": "Hedef",
  "GoCardless Bank Account Data (EU · UK, free tier)": "GoCardless Banka Hesap Verisi (AB · BK, ücretsiz katman)",
  "Gold / oz": "Altın / ons",
  "good": "iyi",
  "Google Calendar": "Google Takvim",
  "Google Calendar API": "Google Takvim API'si",
  "Google Calendar: {} added, {} updated": "Google Takvim: {} eklendi, {} güncellendi",
  "Google did not return an access token": "Google bir erişim anahtarı döndürmedi",
  "Google sign-in was cancelled": "Google oturum açma iptal edildi",
  "Gram gold": "Gram altın",
  "Grateful for": "Minnettar olduğum",
  "great": "harika",
  "Groceries": "Market",
  "Grouped by day. Overdue items float to the top so nothing quietly rots. Edit any task with ✏️, delete with ✕, and step through past or future weeks with ← → to fix old tasks or plan ahead.": "Güne göre gruplanır. Gecikenler en üste çıkar, böylece hiçbir şey sessizce çürümez. Görevleri ✏️ ile düzenle, ✕ ile sil, ← → ile geçmiş ya da gelecek haftalar arasında gezinip eskileri düzelt veya ileriyi planla.",
  "Guest": "Misafir",
  "Guided prompts": "Yönlendirmeli sorular",
  "Gym": "Spor salonu",
  "Gym & Health": "Spor ve Sağlık",
  "Gym & Health budget (£)": "Spor ve sağlık bütçesi (£)",
  "h {}min": "sa {}dk",
  "h sleep": "sa uyku",
  "Habit": "Alışkanlık",
  "Habits": "Alışkanlıklar",
  "Have a look around first": "Önce bir etrafına bak",
  "Headline": "Başlık",
  "Health": "Sağlık",
  "Health & Body": "Sağlık ve Beden",
  "Helper not running — enter today's WHOOP numbers manually (or start": "Yardımcı çalışmıyor — bugünün WHOOP sayılarını elle gir (ya da şunu başlat:",
  "Hesabını kur": "Hesabını kur",
  "Hide": "Gizle",
  "Hide password": "Parolayı gizle",
  "High": "Yüksek",
  "Hit protein target": "Protein hedefini tuttur",
  "Hobbies": "Hobiler",
  "Home-screen widget connected": "Ana ekran bileşeni bağlandı",
  "hour ago": "saat önce",
  "hours ago": "saat önce",
  "How are you feeling today?": "Bugün kendini nasıl hissediyorsun?",
  "How big is your market? Growth rate? Competition landscape?": "Pazarın ne kadar büyük? Büyüme hızı? Rekabet manzarası?",
  "How did today actually go? Write freely — nothing here is logged automatically, and only what you type is saved.": "Bugün gerçekte nasıl geçti? Serbestçe yaz — burada hiçbir şey kendiliğinden kaydedilmez, yalnızca yazdığın saklanır.",
  "How do you make money? Pricing strategy, unit economics, gross margin targets?": "Nasıl para kazanıyorsun? Fiyatlama stratejisi, birim ekonomisi, brüt kâr hedefleri?",
  "How do you want to be perceived? Brand voice, tone, visual style, core values?": "Nasıl algılanmak istiyorsun? Marka sesi, ton, görsel dil, temel değerler?",
  "How far ahead": "Ne kadar ileriye",
  "How has my sleep been?": "Uykum nasıldı?",
  "How I operate": "Nasıl çalışırım",
  "How I operate, expand": "Nasıl çalışırım, genişlet",
  "How to answer:": "Nasıl cevaplanır:",
  "How to write it:": "Nasıl yazılır:",
  "How will you reach customers? Channels, partnerships, customer acquisition strategy?": "Müşterilere nasıl ulaşacaksın? Kanallar, ortaklıklar, müşteri kazanım stratejisi?",
  "How you feel, next to how you slept — the two usually explain each other.": "Nasıl hissettiğin, nasıl uyuduğunun yanında — ikisi genelde birbirini açıklar.",
  "HRV (ms)": "HRV (ms)",
  "Hypertrophy": "Hipertrofi",
  "I already have an account": "Zaten hesabım var",
  "I have a code": "Kodum var",
  "I have written these down somewhere safe": "Bunları güvenli bir yere yazdım",
  "ℹ️ No times logged": "ℹ️ Kayıtlı saat yok",
  "Icon": "Simge",
  "Ideas, blockers, meeting notes, reminders…": "Fikirler, engeller, toplantı notları, hatırlatmalar…",
  "Ideas, context, decisions… (saves automatically as you type)": "Fikirler, bağlam, kararlar… (yazdıkça kendiliğinden kaydedilir)",
  "Import {}": "{} içe aktar",
  "Imported {} expense{}{} ✓": "{} harcama içe aktarıldı{}{} ✓",
  "Imported from statement": "Ekstreden içe aktarıldı",
  "in {} days": "{} gün içinde",
  "in {} months": "{} ay içinde",
  "in {} weeks": "{} hafta içinde",
  "In Claude or ChatGPT, add a custom connector and give it the server URL above.": "Claude ya da ChatGPT'de özel bir bağlayıcı ekle ve yukarıdaki sunucu adresini ver.",
  "In progress": "Devam ediyor",
  "Include": "Dahil et",
  "Invite": "Davet et",
  "invite by email": "e-postayla davet et",
  "Invite code": "Davet kodu",
  "Invited {} ✓": "{} davet edildi ✓",
  "It can see your priorities, this week, your journal, training, habits, sleep, metrics and spending — and answer questions about them. It cannot change anything, which is deliberate.": "Önceliklerini, bu haftanı, günlüğünü, antrenmanını, alışkanlıklarını, uykunu, ölçümlerini ve harcamalarını görebilir — ve bunlar hakkındaki soruları yanıtlayabilir. Hiçbir şeyi değiştiremez; bu bilinçli bir tercih.",
  "It will send you here to sign in and say yes. That is all — no token to copy.": "Seni oturum açıp onaylaman için buraya gönderir. Hepsi bu — kopyalanacak bir anahtar yok.",
  "Jan": "Oca",
  "Journal": "Günlük",
  "JPG · PNG · HEIC · works offline after the first run": "JPG · PNG · HEIC · ilk çalıştırmadan sonra çevrimdışı çalışır",
  "Jul": "Tem",
  "jump to this week": "bu haftaya atla",
  "Jun": "Haz",
  "just now": "az önce",
  "Keep": "Koru",
  "Keep my work — create an account": "Yaptıklarımı koru — hesap oluştur",
  "keep what's working": "işe yarayanı koru",
  "Keeping your work…": "Yaptıkların korunuyor…",
  "Key Value Props": "Temel Değer Önerileri",
  "keys in the same database as the rest of the app, and is mirrored to this browser so it survives going offline.": "anahtarlarında, uygulamanın geri kalanıyla aynı veritabanında durur ve çevrimdışı kalmaya dayanması için bu tarayıcıya yansıtılır.",
  "Languages": "Diller",
  "last {} {} ago": "son {} {} önce",
  "Last 14 days": "Son 14 gün",
  "Last 6 months": "Son 6 ay",
  "Last audit {} — kept {}, changed {}, cut {}. {}": "Son denetim {} — {} korundu, {} değişti, {} kesildi. {}",
  "Last check. There is no undo and no backup. Type your email address ({}) to delete the account:": "Son kontrol. Geri alma yok, yedek yok. Hesabı silmek için e-posta adresini ({}) yaz:",
  "last logged": "son kayıt",
  "last night": "dün gece",
  "last used {}": "son kullanım {}",
  "last week": "geçen hafta",
  "Later": "Sonra",
  "Lean / maintain (1.6 g/kg)": "Yağsız / koru (1,6 g/kg)",
  "Learn more about business": "İş hakkında daha fazlasını öğren",
  "Learned merchants: {} {}": "Öğrenilen satıcılar: {} {}",
  "Learning": "Öğrenme",
  "Leave": "Ayrıl",
  "Left the task": "Görevden ayrıldın",
  "Legs": "Bacak",
  "Leo": "Aslan",
  "Libra": "Terazi",
  "Limit to these tabs (blank = all)": "Şu sekmelerle sınırla (boş = hepsi)",
  "Link copied ✓": "Bağlantı kopyalandı ✓",
  "Links: {}": "Bağlantılar: {}",
  "Live streams": "Canlı yayınlar",
  "Loading your compass…": "Pusulan yükleniyor…",
  "Loading…": "Yükleniyor…",
  "Log": "Kaydet",
  "Log a time block": "Zaman bloğu kaydet",
  "Log last night's sleep": "Dün geceki uykuyu kaydet",
  "Log sleep": "Uykuyu kaydet",
  "Log some time to see your breakdown.": "Dağılımını görmek için biraz zaman kaydet.",
  "Log time block": "Zaman bloğu kaydet",
  "Log today": "Bugünü kaydet",
  "Log where your time goes. See your weekly breakdown at a glance.": "Zamanının nereye gittiğini kaydet. Haftalık dağılımını bir bakışta gör.",
  "Log your sleep and how you feel each morning — and sync WHOOP for live Recovery, Strain & HRV.": "Her sabah uykunu ve nasıl hissettiğini kaydet — canlı Toparlanma, Zorlanma ve HRV için WHOOP'u eşitle.",
  "Logged this week": "Bu hafta kaydedilen",
  "Logged today": "Bugün kaydedilen",
  "Logging since": "Kayıt başlangıcı",
  "loud and square": "yüksek sesli ve köşeli",
  "Low": "Düşük",
  "Make a code": "Kod oluştur",
  "Make a code and send it to one person, or type in the code they sent you.": "Bir kod oluştur ve tek bir kişiye gönder, ya da sana gönderdikleri kodu yaz.",
  "Make sure the file has a header row with a date column and an amount (or debit) column.": "Dosyada bir başlık satırı, bir tarih sütunu ve bir tutar (ya da borç) sütunu olduğundan emin ol.",
  "Make ten new recovery codes? Any codes you were given before stop working straight away. The new ones are shown once.": "On yeni kurtarma kodu oluşturulsun mu? Daha önce aldığın kodlar anında çalışmayı bırakır. Yenileri bir kez gösterilir.",
  "Manual": "Elle",
  "Mar": "Mar",
  "Mark done": "Bitti işaretle",
  "Market Opportunity": "Pazar Fırsatı",
  "masculine": "eril",
  "May": "May",
  "Meal": "Öğün",
  "Meal plan saved ✓": "Beslenme planı kaydedildi ✓",
  "Meal template — from your diet plan:": "Öğün şablonu — beslenme planından:",
  "Med": "Orta",
  "Merchant": "Satıcı",
  "Merchant / description": "Satıcı / açıklama",
  "Merchant memory cleared": "Satıcı hafızası temizlendi",
  "Message": "Mesaj",
  "Metric": "Ölçüt",
  "min": "dk",
  "min ago": "dk önce",
  "MINIMIZE — delegate or batch into one slot": "AZALT — devret ya da tek bir slota topla",
  "Minutes": "Dakika",
  "Mission and roles": "Misyon ve roller",
  "Model \"{}\" is not available on this key. Set FLOW_CHAT_MODEL in Render to one that is.": "\"{}\" modeli bu anahtarda kullanılamıyor. Render'da FLOW_CHAT_MODEL'i kullanılabilir bir modele ayarla.",
  "Mon": "Pzt",
  "Monday": "Pazartesi",
  "Money": "Para",
  "monospaced": "eşaralıklı",
  "Month-first (US)": "Önce ay (ABD)",
  "Monthly budget": "Aylık bütçe",
  "Monthly income": "Aylık gelir",
  "Monthly income (£)": "Aylık gelir (£)",
  "Monthly spend": "Aylık harcama",
  "Mood": "Ruh hali",
  "mood {}/5 {}": "ruh hali {}/5 {}",
  "Mood & Energy": "Ruh Hali ve Enerji",
  "Mood & Energy — last {} days": "Ruh Hali ve Enerji — son {} gün",
  "Mood & Energy — today": "Ruh Hali ve Enerji — bugün",
  "Mood and energy": "Ruh hali ve enerji",
  "More": "Daha fazla",
  "Most time spent on": "En çok zaman ayrılan",
  "most weeks": "çoğu hafta",
  "Move to another quadrant": "Başka bir çeyreğe taşı",
  "Music": "Müzik",
  "Music production": "Müzik prodüksiyonu",
  "My North Star": "Kuzey Yıldızım",
  "Name": "Ad",
  "Name | sets × reps": "Ad | set × tekrar",
  "never happened": "hiç olmadı",
  "never used": "hiç kullanılmadı",
  "New conversation": "Yeni sohbet",
  "New journal note: “{}”": "Yeni günlük notu: “{}”",
  "New password": "Yeni parola",
  "New password (at least 10 characters):": "Yeni parola (en az 10 karakter):",
  "New section": "Yeni bölüm",
  "New target": "Yeni hedef",
  "Next": "Sonraki",
  "Next →": "Sonraki →",
  "Next 12 weeks": "Gelecek 12 hafta",
  "Next 2 weeks": "Gelecek 2 hafta",
  "Next 4 weeks": "Gelecek 4 hafta",
  "Next due {}.": "Sıradaki {}.",
  "next week": "gelecek hafta",
  "No": "Hayır",
  "No access tokens. Nothing needs one unless a client cannot sign in for itself.": "Erişim anahtarı yok. Kendi başına oturum açamayan bir istemci olmadıkça hiçbir şeyin buna ihtiyacı yok.",
  "No account, nothing saved to the server. You can keep your work if you sign up afterwards.": "Hesap yok, sunucuya hiçbir şey kaydedilmiyor. Sonradan kaydolursan yaptıkların korunabilir.",
  "No big rocks set yet. Add 1–3 in 🧭 Week Compass — the most important things to move this week.": "Henüz büyük kaya yok. 🧭 Hafta Pusulası'na 1–3 tane ekle — bu hafta ilerletilecek en önemli şeyler.",
  "No big rocks yet for this week. Add 1–3 per role above — or send items over from 🎯 Priorities.": "Bu hafta için henüz büyük kaya yok. Yukarıda rol başına 1–3 tane ekle — ya da 🎯 Öncelikler'den madde gönder.",
  "No comments yet.": "Henüz yorum yok.",
  "No data yet": "Henüz veri yok",
  "No entries match that search.": "Bu aramayla eşleşen kayıt yok.",
  "No entries to export.": "Dışa aktarılacak kayıt yok.",
  "No entries yet — log your first time block above.": "Henüz kayıt yok — yukarıdan ilk zaman bloğunu gir.",
  "No entries yet.": "Henüz kayıt yok.",
  "No exercises written yet — hit ✏️ Edit this day.": "Henüz hareket yazılmadı — ✏️ Bu günü düzenle'ye bas.",
  "No expenses logged this month yet.": "Bu ay henüz harcama kaydedilmedi.",
  "No expenses logged this month.": "Bu ay harcama kaydedilmedi.",
  "No expenses yet — snap a receipt or import a statement above.": "Henüz harcama yok — yukarıdan bir fiş çek ya da ekstre içe aktar.",
  "No habits yet — add your first one above.": "Henüz alışkanlık yok — yukarıdan ilkini ekle.",
  "No habits yet. Add them in ✅ Habits and they show up here.": "Henüz alışkanlık yok. ✅ Alışkanlıklar'da ekle, burada görünürler.",
  "No journal entries yet — log something in any tab.": "Henüz günlük kaydı yok — herhangi bir sekmede bir şey kaydet.",
  "No lines yet. Tap": "Henüz satır yok. Şuna dokun:",
  "No links yet.": "Henüz bağlantı yok.",
  "No longer paired with {}.": "{} ile eşleşme sona erdi.",
  "No meal plan yet — write your own program here (meals, timing, macros), or just use the daily checklist above.": "Henüz beslenme planı yok — kendi programını buraya yaz (öğünler, saatler, makrolar) ya da yukarıdaki günlük listeyi kullan.",
  "No meal plan yet. Write your own here later, or just use the daily checklist above.": "Henüz beslenme planı yok. Sonra kendininkini buraya yaz ya da yukarıdaki günlük listeyi kullan.",
  "No nights logged yet — add one above and this fills in.": "Henüz gece kaydedilmedi — yukarıdan bir tane ekle, burası dolsun.",
  "No scheduled items in that range yet.": "Bu aralıkta henüz planlı madde yok.",
  "No sections yet.": "Henüz bölüm yok.",
  "No spending rows recognised. Columns found: {}.": "Harcama satırı tanınmadı. Bulunan sütunlar: {}.",
  "no target": "hedef yok",
  "no target set": "hedef belirlenmedi",
  "Nobody is paired with you yet. Make a code below and send it to one person — it works once, then it is spent.": "Henüz kimseyle eşleşmedin. Aşağıdan bir kod oluştur ve tek bir kişiye gönder — bir kez çalışır, sonra biter.",
  "nobody yet": "henüz kimse",
  "None — statement import only (recommended)": "Hiçbiri — yalnızca ekstre içe aktarma (önerilir)",
  "none set": "ayarlı değil",
  "none yet": "henüz yok",
  "North Star": "Kuzey Yıldızı",
  "not once": "bir kez bile",
  "Not saved yet": "Henüz kaydedilmedi",
  "Note": "Not",
  "Note (optional)": "Not (isteğe bağlı)",
  "Note for this action item… (saves as you type)": "Bu aksiyon maddesi için not… (yazdıkça kaydedilir)",
  "Notes": "Notlar",
  "Notes (optional)": "Notlar (isteğe bağlı)",
  "Notes saved ✓": "Notlar kaydedildi ✓",
  "Notes: {}": "Notlar: {}",
  "nothing for today yet": "bugün için henüz bir şey yok",
  "Nothing here yet": "Burada henüz bir şey yok",
  "Nothing is added to your app until you press Add.": "Ekle'ye basana kadar uygulamana hiçbir şey eklenmez.",
  "nothing logged": "kayıt yok",
  "Nothing logged this month yet.": "Bu ay henüz bir şey kaydedilmedi.",
  "Nothing logged yet — rate a day above and this fills in.": "Henüz kayıt yok — yukarıdan bir güne puan ver, burası dolsun.",
  "Nothing matches that.": "Bununla eşleşen bir şey yok.",
  "nothing on the clock yet": "sayaçta henüz bir şey yok",
  "Nothing open in Q1 or Q2. Star a Planner task or add them in 🎯 Priorities.": "Q1 ya da Q2'de açık bir şey yok. Bir Planlayıcı görevini yıldızla ya da 🎯 Öncelikler'e ekle.",
  "Nothing planned": "Planlanmış bir şey yok",
  "Nothing scheduled for today. Give a task a time with the 🕘 chip on any tab, or add one below.": "Bugün için planlanmış bir şey yok. Herhangi bir sekmede 🕘 etiketiyle bir göreve saat ver ya da aşağıdan ekle.",
  "Nothing scheduled that week.": "O hafta planlanmış bir şey yok.",
  "Nothing set for today": "Bugün için bir şey ayarlanmadı",
  "Nothing set for today.": "Bugün için bir şey ayarlanmadı.",
  "Nothing shared yet.": "Henüz bir şey paylaşılmadı.",
  "Nothing shared yet. Type a task above and share it — you get a link to send, or invite by email.": "Henüz bir şey paylaşılmadı. Yukarıya bir görev yaz ve paylaş — gönderebileceğin bir bağlantı alırsın ya da e-postayla davet et.",
  "Nothing to chart yet.": "Henüz grafiğe dökülecek bir şey yok.",
  "Nothing to send — schedule something first.": "Gönderilecek bir şey yok — önce bir şey planla.",
  "nothing urgent": "acil bir şey yok",
  "Nothing urgent": "Acil bir şey yok",
  "Nothing waiting. When somebody shares a task with you it appears here.": "Bekleyen bir şey yok. Biri seninle bir görev paylaştığında burada görünür.",
  "Nothing written yet. The box above is the whole point — write a few lines about today and press Save entry.": "Henüz bir şey yazılmadı. Yukarıdaki kutu meselenin ta kendisi — bugün hakkında birkaç satır yaz ve Kaydı kaydet'e bas.",
  "Nov": "Kas",
  "OAuth client ID": "OAuth istemci kimliği",
  "OAuth Client ID": "OAuth İstemci Kimliği",
  "OAuth consent screen → External → add yourself as a test user.": "OAuth onay ekranı → Harici → kendini test kullanıcısı olarak ekle.",
  "Oct": "Eki",
  "of {} days": "{} günden",
  "of {} decided": "{} karardan",
  "of {} decided. Finish it while the last {} months are still in front of you.": "{} karardan. Son {} ay hâlâ önündeyken bitir.",
  "of {} on target": "{} hedeften",
  "of {} this {}": "{} içinden, bu {}",
  "ok": "idare eder",
  "OK": "Tamam",
  "One line describing it": "Bir satırla tarif et",
  "One moment…": "Bir saniye…",
  "One of the codes you were given when you signed up. Case and dashes do not matter.": "Kaydolurken sana verilen kodlardan biri. Büyük-küçük harf ve tireler önemli değil.",
  "one per line:": "her satıra bir tane:",
  "One per line. Changing a category on any expense also teaches the matcher that merchant, so imports get sharper over time.": "Her satıra bir tane. Bir harcamanın kategorisini değiştirmek eşleştiriciye o satıcıyı da öğretir, böylece içe aktarmalar zamanla keskinleşir.",
  "One tap each time you do the thing. Weeks run Monday to Sunday. Tap the name to rename it or change the target.": "O şeyi her yaptığında bir dokunuş. Haftalar Pazartesiden Pazara işler. Adını değiştirmek ya da hedefi güncellemek için ada dokun.",
  "One thing for tomorrow": "Yarın için bir şey",
  "Open": "Aç",
  "Open it": "Aç",
  "Open Q2 priorities": "Açık Q2 öncelikleri",
  "Open tasks": "Açık görevler",
  "Open The Flow": "The Flow'u aç",
  "Open the full matrix →": "Tam matrisi aç →",
  "Open the Priorities matrix once to start sorting what matters.": "Neyin önemli olduğunu ayırmaya başlamak için Öncelikler matrisini bir kez aç.",
  "Optional": "İsteğe bağlı",
  "Optional due date": "İsteğe bağlı bitiş tarihi",
  "Optional note — what's shaping today? (sleep, stress, workout, food...)": "İsteğe bağlı not — bugünü ne şekillendiriyor? (uyku, stres, antrenman, yemek...)",
  "or": "ya da",
  "Original widgets restored": "Orijinal bileşenler geri getirildi",
  "Other": "Diğer",
  "Other budget (£)": "Diğer bütçe (£)",
  "Outbox published — {} item{} ready at {}": "Giden kutusu yayınlandı — {} madde{} şurada hazır: {}",
  "Over budget by {} left this month": "Bütçe {} aşıldı, bu ay kalan",
  "Overdue": "Gecikmiş",
  "overdue · {}": "gecikmiş · {}",
  "Pair": "Eşleş",
  "Pair with someone": "Biriyle eşleş",
  "Paired with {} ✓": "{} ile eşleşildi ✓",
  "Password": "Parola",
  "Password changed ✓": "Parola değiştirildi ✓",
  "Paste a link… (Enter)": "Bir bağlantı yapıştır… (Enter)",
  "Paste the client ID above. No client secret is needed — the token never leaves your browser.": "İstemci kimliğini yukarıya yapıştır. İstemci parolası gerekmez — anahtar tarayıcından hiç çıkmaz.",
  "Per": "Başına",
  "per month": "ayda",
  "per week": "haftada",
  "Performances": "Performanslar",
  "Pick a colour theme. It applies the instant you tap it — no reload — and is saved to your account (or kept on this device while you're just looking around).": "Bir renk teması seç. Dokunduğun anda uygulanır — sayfa yenilenmez — ve hesabına kaydedilir (ya da sadece dolaşıyorsan bu cihazda tutulur).",
  "Pisces": "Balık",
  "Plaid (US · CA · UK · EU)": "Plaid (ABD · Kanada · BK · AB)",
  "Plan": "Plan",
  "Plan for week {}": "{}. hafta planı",
  "Planned": "Planlanan",
  "Every task is urgent or not, and important or not — that gives four boxes. Q1 is both: fires and deadlines, the things that break if you ignore them. Do them now. Q2 is important but never urgent — planning, training, learning, the people who matter. Nothing forces you to do it, which is why it gets skipped, and why it is the box that decides how your year goes. Schedule it on purpose. Q3 is urgent but not important to you — other people's priorities landing on your desk. Delegate it, or batch it into one slot. Q4 is neither: fine as a reward, once the real work is placed. \"→ Rock\" sends an item to the week you're viewing in the Compass.": "Her iş ya acildir ya değildir, ya önemlidir ya değildir — bu da dört kutu eder. Q1 ikisi birden: yangınlar ve teslim tarihleri, görmezden gelirsen kırılan şeyler. Şimdi yap. Q2 önemli ama hiçbir zaman acil değil — planlama, antrenman, öğrenme, önemsediğin insanlar. Seni yapmaya zorlayan bir şey yok; atlanmasının sebebi de bu, yılının nasıl geçeceğine karar veren kutu olmasının sebebi de. Bilerek takvime koy. Q3 acil ama senin için önemli değil — başkalarının öncelikleri masana düşüyor. Devret ya da tek bir slota topla. Q4 ikisi de değil: asıl iş yerleştikten sonra bir ödül olarak iyidir. \"→ Kaya\", bir maddeyi Pusula'da baktığın haftaya gönderir.",
  "Preferences · integrations · data": "Tercihler · entegrasyonlar · veri",
  "Previous": "Önceki",
  "Prices load when the server wakes up.": "Fiyatlar sunucu uyandığında yüklenir.",
  "Priorities": "Öncelikler",
  "Priorities (Q1–Q4)": "Öncelikler (Q1–Q4)",
  "Priority": "Öncelik",
  "priority · {}": "öncelik · {}",
  "Problem I Solve": "Çözdüğüm Problem",
  "Protein within ~3 h of bed": "Yatmadan ~3 sa önce protein",
  "Publish outbox now": "Giden kutusunu şimdi yayınla",
  "Pull": "Çekiş",
  "Pull — Back and Biceps": "Çekiş — Sırt ve Biseps",
  "Push": "İtiş",
  "Push — Chest, Shoulders, Triceps": "İtiş — Göğüs, Omuz, Triseps",
  "Pushing…": "Gönderiliyor…",
  "Q1 — Urgent & Important": "Q1 — Acil ve Önemli",
  "Q1 · urgent": "Q1 · acil",
  "Q2 — Not Urgent & Important": "Q2 — Acil Değil ve Önemli",
  "Q3 — Urgent & Not Important": "Q3 — Acil ve Önemli Değil",
  "Q4 — Not Urgent & Not Important": "Q4 — Acil Değil ve Önemli Değil",
  "Quality": "Kalite",
  "quiet blue": "sakin mavi",
  "Range": "Aralık",
  "Re-render breakdown widgets": "Dağılım bileşenlerini yeniden çiz",
  "Reaching the server…": "Sunucuya ulaşılıyor…",
  "Read from the photo": "Fotoğraftan oku",
  "Read straight off your existing tabs as they stand right now — no duplicate data entry.": "Doğrudan mevcut sekmelerinden, şu anki halleriyle okunur — ikinci kez veri girmek yok.",
  "Reading the last eight weeks…": "Son sekiz hafta okunuyor…",
  "Reading the text on your device… the first run downloads the language data, which takes a moment.": "Metin cihazında okunuyor… ilk çalıştırma dil verisini indirir, bu biraz sürer.",
  "Reading your backup": "Yedeğin okunuyor",
  "Reading your week…": "Haftan okunuyor…",
  "Really erase? This cannot be undone.": "Gerçekten silinsin mi? Bu geri alınamaz.",
  "Receipt photo": "Fiş fotoğrafı",
  "Receipt saved ✓": "Fiş kaydedildi ✓",
  "Recent activity log (newest last)": "Son etkinlik kaydı (en yenisi sonda)",
  "Recent entries": "Son kayıtlar",
  "Recent expenses": "Son harcamalar",
  "Recent nights": "Son geceler",
  "recognizing text": "metin tanınıyor",
  "Record": "Kayıt",
  "Recover": "Kurtar",
  "Recovered {} journal entries and all your sections. Refreshing now…": "{} günlük kaydı ve tüm bölümlerin kurtarıldı. Şimdi yenileniyor…",
  "Recovery": "Toparlanma",
  "Recovery %": "Toparlanma %",
  "Recovery code": "Kurtarma kodu",
  "Recovery codes": "Kurtarma kodları",
  "Redo": "Yinele",
  "Refreshing the app": "Uygulama yenileniyor",
  "Relationships": "İlişkiler",
  "Remaining": "Kalan",
  "Remaining budget": "Kalan bütçe",
  "Remind me about this section": "Bu bölümü bana hatırlat",
  "Reminders list name": "Hatırlatıcılar listesinin adı",
  "Remove": "Kaldır",
  "Remove the reminder": "Hatırlatıcıyı kaldır",
  "Remove this line": "Bu satırı kaldır",
  "Rename": "Yeniden adlandır",
  "Rent & Bills": "Kira ve Faturalar",
  "Repeat with Each": "Her Biri İçin Tekrarla",
  "Request failed ({})": "İstek başarısız ({})",
  "Reset": "Sıfırla",
  "Reset to the blank template": "Boş şablona sıfırla",
  "Reset to the template ✓": "Şablona sıfırlandı ✓",
  "Reset week ticks": "Hafta işaretlerini sıfırla",
  "Reset your training, diet, weekly commitments and board names to the blank template? Your journal, tasks and finances are not touched.": "Antrenmanın, beslenmen, haftalık taahhütlerin ve pano adların boş şablona sıfırlansın mı? Günlüğün, görevlerin ve finansların etkilenmez.",
  "Rest": "Dinlenme",
  "Rest / Active Recovery": "Dinlenme / Aktif Toparlanma",
  "rest day": "dinlenme günü",
  "Rest day": "Dinlenme günü",
  "Rest day — recover well.": "Dinlenme günü — iyi toparlan.",
  "Resting HR": "Dinlenme nabzı",
  "Restore": "Geri yükle",
  "Restore from a backup file": "Bir yedek dosyasından geri yükle",
  "Restore the originals": "Orijinalleri geri getir",
  "Restored!": "Geri yüklendi!",
  "Restoring your data…": "Verilerin geri yükleniyor…",
  "Retry": "Tekrar dene",
  "Revenue Model": "Gelir Modeli",
  "Revoke": "İptal et",
  "Revoke \"{}\"? Anything using it stops working straight away. Nothing you have saved is affected.": "\"{}\" iptal edilsin mi? Onu kullanan her şey anında çalışmayı bırakır. Kaydettiğin hiçbir şey etkilenmez.",
  "Revoked ✓": "İptal edildi ✓",
  "Rewrite it": "Yeniden yaz",
  "Right now": "Şu anda",
  "Ring": "Halka",
  "rough": "zor",
  "Routine audit": "Rutin denetimi",
  "Routine audit, expand": "Rutin denetimi, genişlet",
  "Run one anyway": "Yine de çalıştır",
  "Sagittarius": "Yay",
  "Salt Edge (widest, includes Turkey)": "Salt Edge (en geniş, Türkiye dahil)",
  "Sat": "Cmt",
  "Saturday": "Cumartesi",
  "Save": "Kaydet",
  "Save budget": "Bütçeyi kaydet",
  "Save entry": "Kaydı kaydet",
  "Save expense + receipt": "Harcamayı ve fişi kaydet",
  "Save goal": "Hedefi kaydet",
  "Save mission": "Misyonu kaydet",
  "Save my setup": "Kurulumumu kaydet",
  "Save notes": "Notları kaydet",
  "Save plan": "Planı kaydet",
  "Save problem": "Problemi kaydet",
  "Save review": "Gözden geçirmeyi kaydet",
  "Save sleep": "Uykuyu kaydet",
  "Save to journal": "Günlüğe kaydet",
  "Saved": "Kaydedildi",
  "Saved — this is your setup now ✓": "Kaydedildi — kurulumun artık bu ✓",
  "Saved {}": "Kaydedildi {}",
  "Saved ✓": "Kaydedildi ✓",
  "Saved locally (offline)": "Yerel olarak kaydedildi (çevrimdışı)",
  "Saved on this device — will sync when back online": "Bu cihaza kaydedildi — çevrimiçi olunca eşitlenecek",
  "Saved to your journal ✓": "Günlüğüne kaydedildi ✓",
  "Saving to the cloud database. Every device signed into this account sees the same data.": "Bulut veritabanına kaydediliyor. Bu hesaba giriş yapmış her cihaz aynı veriyi görür.",
  "Saving to your cloud database": "Bulut veritabanına kaydediliyor",
  "Saving to your cloud…": "Buluta kaydediliyor…",
  "Saving…": "Kaydediliyor…",
  "Say something first.": "Önce bir şey söyle.",
  "SCHEDULE — this is where you win": "PLANLA — kazandığın yer burası",
  "Schedule cleared": "Plan temizlendi",
  "Schedule this — adds a date, time and duration you can export to your calendar": "Bunu planla — takvimine aktarabileceğin bir tarih, saat ve süre ekler",
  "Scheduled ✓": "Planlandı ✓",
  "scheduled task": "planlı görev",
  "scheduled tasks": "planlı görevler",
  "Scheduled this week": "Bu hafta planlanan",
  "Scheduled today": "Bugün planlanan",
  "Scoreboard": "Skor tablosu",
  "Scoreboard{}": "Skor tablosu{}",
  "Scorpio": "Akrep",
  "Search": "Ara",
  "Search your entries…": "Kayıtlarında ara…",
  "Section title…": "Bölüm başlığı…",
  "Send": "Gönder",
  "Send one of these to one person. Each works once and expires in two weeks.": "Bunlardan birini tek bir kişiye gönder. Her biri bir kez çalışır ve iki hafta sonra geçersiz olur.",
  "Send to the Compass week you are viewing": "Baktığın Pusula haftasına gönder",
  "send-outs": "gönderimler",
  "Sending…": "Gönderiliyor…",
  "Sent — the link works once, for 30 minutes.": "Gönderildi — bağlantı bir kez ve 30 dakika boyunca çalışır.",
  "Sep": "Eyl",
  "Server URL": "Sunucu adresi",
  "sessions": "seans",
  "Sessions": "Seanslar",
  "Sessions this week": "Bu haftaki seanslar",
  "Set": "Set",
  "Set a monthly budget in Settings to track it here.": "Burada takip etmek için Ayarlar'dan aylık bütçe belirle.",
  "Set a new password": "Yeni bir parola belirle",
  "Set category budgets in 💰 Finances to track this against a limit.": "Bunu bir sınıra göre izlemek için 💰 Finans'ta kategori bütçeleri belirle.",
  "Set new password": "Yeni parola belirle",
  "Set up": "Kurulum",
  "Set up your account": "Hesabını kur",
  "sets": "set",
  "Settings": "Ayarlar",
  "Share a new task with someone…": "Biriyle yeni bir görev paylaş…",
  "Share task": "Görevi paylaş",
  "Shared ✓": "Paylaşıldı ✓",
  "Shared ✓ link copied": "Paylaşıldı ✓ bağlantı kopyalandı",
  "Shared by {}{} · {} {} · updated {}": "Paylaşan {}{} · {} {} · güncellendi {}",
  "Sharpen the Blade": "Baltayı Bile",
  "Sharpen the Blade, expand": "Baltayı Bile, genişlet",
  "Shopping": "Alışveriş",
  "Shopping budget (£)": "Alışveriş bütçesi (£)",
  "Shortcuts → new shortcut →": "Kısayollar → yeni kısayol →",
  "Show": "Göster",
  "Show password": "Parolayı göster",
  "Show time chips on task rows": "Görev satırlarında zaman etiketlerini göster",
  "Showing": "Gösteriliyor",
  "Showing the latest 500 of {} entries — everything is kept; use Export for the full history.": "{} kaydın son 500 tanesi gösteriliyor — hepsi saklanıyor; tam geçmiş için Dışa aktar'ı kullan.",
  "shows": "gösteri",
  "Side Project": "Yan Proje",
  "Sign in": "Giriş yap",
  "Sign in to The Flow": "The Flow'a giriş yap",
  "Sign out": "Çıkış yap",
  "Sign out of The Flow on this device?": "Bu cihazda The Flow oturumu kapatılsın mı?",
  "Signed in as": "Oturum açan",
  "Signing in…": "Giriş yapılıyor…",
  "Six months of things you do every day are sitting in the record. Keep what's working, get rid of what isn't.": "Her gün yaptığın şeylerin altı ayı kayıtta duruyor. İşe yarayanı koru, yaramayanı at.",
  "Skips the file — signs you in and adds your scheduled tasks to Google directly": "Dosyayı atlar — oturumunu açar ve planlı görevlerini doğrudan Google'a ekler",
  "Sleep": "Uyku",
  "Sleep & mood": "Uyku ve ruh hali",
  "Sleep & Mood": "Uyku ve Ruh Hali",
  "Sleep %": "Uyku %",
  "Sleep debt (7d)": "Uyku borcu (7g)",
  "Sleep hours": "Uyku saati",
  "Sleep hours — last {} nights": "Uyku saatleri — son {} gece",
  "Sleep hours — last 14 nights": "Uyku saatleri — son 14 gece",
  "Sleep hours — last night": "Uyku saatleri — dün gece",
  "Sleep Perf": "Uyku Perf.",
  "Slipping": "Kayıyor",
  "Social": "Sosyal",
  "soft light": "yumuşak aydınlık",
  "Something broke rendering this tab": "Bu sekme çizilirken bir şey bozuldu",
  "Something creative": "Yaratıcı bir şey",
  "Something important but not urgent — this is where the wins are": "Önemli ama acil olmayan bir şey — kazançlar buradadır",
  "Something that is neither — be honest about it": "Hiçbiri olmayan bir şey — bu konuda dürüst ol",
  "Something urgent and important — do it today": "Acil ve önemli bir şey — bugün yap",
  "Something urgent but not important — can it be delegated?": "Acil ama önemli olmayan bir şey — devredilebilir mi?",
  "Something went wrong ({})": "Bir şeyler ters gitti ({})",
  "Something went wrong.": "Bir şeyler ters gitti.",
  "Spend": "Harcama",
  "Spending by category": "Kategoriye göre harcama",
  "Spent this month": "Bu ay harcanan",
  "sporty": "sportif",
  "stark black": "keskin siyah",
  "Starred": "Yıldızlı",
  "Start the audit": "Denetimi başlat",
  "Start time": "Başlangıç saati",
  "Statement date format": "Ekstre tarih biçimi",
  "Stop for now": "Şimdilik dur",
  "Stored right now: {} scheduled items · {} expenses · {} notebooks · {} unsynced change{}": "Şu anda saklanan: {} planlı madde · {} harcama · {} defter · {} eşitlenmemiş değişiklik{}",
  "Straight from your Eisenhower matrix — the same list your Today screen pulls from.": "Doğrudan Eisenhower matrisinden — Bugün ekranının çektiği listenin aynısı.",
  "Strain": "Zorlanma",
  "Strategic questions to clarify your business: who you serve, what problem you solve, who you are, and what makes you different.": "İşini netleştiren stratejik sorular: kime hizmet ediyorsun, hangi problemi çözüyorsun, kimsin ve seni farklı kılan ne.",
  "Streak ≥ 80%": "Seri ≥ %80",
  "streams": "yayın",
  "Strength": "Kuvvet",
  "Stretch or walk": "Esne ya da yürü",
  "Sub-section": "Alt bölüm",
  "Subscriptions": "Abonelikler",
  "Subscriptions budget (£)": "Abonelik bütçesi (£)",
  "Sun": "Paz",
  "Sunday": "Pazar",
  "Supplements": "Takviyeler",
  "Switched off is not sent — it is not hidden on their screen, it never leaves here.": "Kapalı olan gönderilmez — karşı tarafın ekranında gizlenmiş değildir, buradan hiç çıkmaz.",
  "Synced {} offline change{} ✓": "{} çevrimdışı değişiklik{} eşitlendi ✓",
  "Syncing {}/{}…": "Eşitleniyor {}/{}…",
  "Tab": "Sekme",
  "Tab names available:": "Kullanılabilir sekme adları:",
  "Tab names available: {}": "Kullanılabilir sekme adları: {}",
  "Tags, comma separated — e.g. training, work, music": "Etiketler, virgülle ayrılmış — ör. antrenman, iş, müzik",
  "Take me to The Flow": "Beni The Flow'a götür",
  "Tap to set progress": "İlerlemeyi ayarlamak için dokun",
  "Tap to take a photo or choose an image": "Fotoğraf çekmek ya da görsel seçmek için dokun",
  "Target": "Hedef",
  "target → {}": "hedef → {}",
  "Target Audience": "Hedef Kitle",
  "Task": "Görev",
  "Tasks": "Görevler",
  "Taurus": "Boğa",
  "tech": "teknoloji",
  "Test CalDAV push": "CalDAV göndermeyi dene",
  "that app": "o uygulama",
  "That code is not right.": "Bu kod doğru değil.",
  "That did not work.": "Bu işe yaramadı.",
  "That doesn’t look like a valid backup file. Pick your RECOVERmydata.json and try again.": "Bu geçerli bir yedek dosyasına benzemiyor. RECOVERmydata.json dosyanı seç ve tekrar dene.",
  "That email and password do not match.": "Bu e-posta ve parola eşleşmiyor.",
  "That file could not be read: {}": "Bu dosya okunamadı: {}",
  "That file is not an image": "Bu dosya bir görsel değil",
  "That invite code is not right.": "Bu davet kodu doğru değil.",
  "That item is gone.": "Bu madde artık yok.",
  "That password is not right.": "Bu parola doğru değil.",
  "that token": "o anahtar",
  "The 🕘 chip is what puts a date, time, duration and alert on tasks that never had one — it is added to every checkbox row across every tab.": "🕘 etiketi, hiç tarihi olmayan görevlere tarih, saat, süre ve uyarı koyan şeydir — her sekmedeki her onay kutusu satırına eklenir.",
  "The API key was rejected. Check ANTHROPIC_API_KEY in Render.": "API anahtarı reddedildi. Render'daki ANTHROPIC_API_KEY'i kontrol et.",
  "The assistant could not answer just now (upstream {}).": "Asistan şu anda cevap veremedi (sunucu {}).",
  "The assistant is not switched on. Add ANTHROPIC_API_KEY in Render to enable it.": "Asistan açık değil. Etkinleştirmek için Render'a ANTHROPIC_API_KEY ekle.",
  "The assistant stopped part-way through.": "Asistan yarıda durdu.",
  "The code you were given": "Sana verilen kod",
  "The dashboard ships as a template. Everything below is yours alone — changing it never touches anyone else's Flow.{}": "Panel bir şablon olarak gelir. Aşağıdaki her şey yalnızca senindir — değiştirmen başkasının Flow'una asla dokunmaz.{}",
  "The direction could not be written just now (upstream {}).": "Yön şu anda yazılamadı (sunucu {}).",
  "The direction could not be written just now.": "Yön şu anda yazılamadı.",
  "The Flow logo": "The Flow logosu",
  "The handful of things that actually move you. Tap a bar to set where you are, or nudge it with − / +.": "Seni gerçekten ilerleten birkaç şey. Nerede olduğunu ayarlamak için bir çubuğa dokun ya da − / + ile oynat.",
  "The next one is due.": "Sıradakinin zamanı geldi.",
  "The one line you write above, for today only.": "Yukarıya yazdığın tek satır, yalnızca bugün için.",
  "the original": "aslı",
  "The principles to re-read when the day tries to pull you off course.": "Gün seni yolundan çıkarmaya çalıştığında yeniden okunacak ilkeler.",
  "The rest of the week is open.": "Haftanın kalanı boş.",
  "The server pushes straight into an iCloud Reminders list. Credentials live in Render environment variables and never touch the browser:": "Sunucu doğrudan bir iCloud Hatırlatıcılar listesine yazar. Kimlik bilgileri Render ortam değişkenlerinde durur ve tarayıcıya hiç uğramaz:",
  "The upkeep that keeps the rest of it possible. Ticks reset every Monday.": "Geri kalan her şeyi mümkün kılan bakım. İşaretler her Pazartesi sıfırlanır.",
  "There is nothing recurring to audit yet — add a metric to the scoreboard or a habit first.": "Denetlenecek tekrar eden bir şey henüz yok — önce skor tablosuna bir ölçüt ya da bir alışkanlık ekle.",
  "These are the way back in if you ever forget your password. Each one works once. Put them somewhere that is not this browser — printed, or in a password manager alongside the password itself.": "Parolanı unutursan geri dönüş yolun bunlar. Her biri bir kez çalışır. Bu tarayıcı dışında bir yere koy — yazdır ya da parolanın yanında bir parola yöneticisine kaydet.",
  "These edits are saved on this device only. They will be sent as soon as the server answers — tap to try now.": "Bu değişiklikler yalnızca bu cihazda kayıtlı. Sunucu cevap verir vermez gönderilecek — şimdi denemek için dokun.",
  "This browser is not signed in, so nothing is being saved to your account. Sign in to sync.": "Bu tarayıcıda oturum açılmadı, bu yüzden hesabına hiçbir şey kaydedilmiyor. Eşitlemek için giriş yap.",
  "This browser would not let me use the clipboard — the codes are selected, so copy them by hand.": "Bu tarayıcı panoyu kullanmama izin vermedi — kodlar seçili, elle kopyala.",
  "This can take a few seconds — please keep this open.": "Bu birkaç saniye sürebilir — lütfen bunu açık tut.",
  "This deletes your account and everything in it, permanently. Type your password to continue:": "Bu, hesabını ve içindeki her şeyi kalıcı olarak siler. Devam etmek için parolanı yaz:",
  "This fills in as soon as there is something to break down.": "Dağıtılacak bir şey olur olmaz burası dolar.",
  "This is the first account on this server, so it becomes the owner — everything already in The Flow becomes yours.": "Bu sunucudaki ilk hesap bu, yani sahibi oluyor — The Flow'da zaten olan her şey senin oluyor.",
  "This link works once and stops working 30 minutes after it was sent. Setting a password here also signs you out everywhere else.": "Bu bağlantı bir kez çalışır ve gönderildikten 30 dakika sonra geçersiz olur. Burada parola belirlemek seni diğer her yerde de oturumdan çıkarır.",
  "this month": "bu ay",
  "This month": "Bu ay",
  "This server is full.": "Bu sunucu dolu.",
  "this week": "bu hafta",
  "This week": "Bu hafta",
  "This week — by category": "Bu hafta — kategoriye göre",
  "This Week · Big Rocks": "Bu Hafta · Büyük Kayalar",
  "This Week · Plan": "Bu Hafta · Plan",
  "This week's plan": "Bu haftanın planı",
  "This week's plan and how many Big Rocks are done.": "Bu haftanın planı ve kaç Büyük Kaya'nın bittiği.",
  "This week's rocks": "Bu haftanın kayaları",
  "Thu": "Per",
  "Thursday": "Perşembe",
  "Tick off your daily basics. Edit the checklist in ⚙️ Settings → Make it yours.": "Günlük temellerini işaretle. Listeyi ⚙️ Ayarlar → Kendine göre ayarla bölümünden düzenle.",
  "Tick what you want, download the file, open it. Everything lands in Apple Calendar or Google Calendar.": "İstediklerini işaretle, dosyayı indir, aç. Her şey Apple Takvim ya da Google Takvim'e düşer.",
  "Ticked": "İşaretlenen",
  "Time": "Zaman",
  "Time committed": "Ayrılan zaman",
  "Time zone": "Saat dilimi",
  "Title": "Başlık",
  "Title (optional) — e.g. 'Hard session, good call'": "Başlık (isteğe bağlı) — ör. 'Zor seans, doğru karar'",
  "To": "Kime",
  "To do": "Yapılacak",
  "to tick": "işaretlenecek",
  "Today": "Bugün",
  "Today · {}": "Bugün · {}",
  "Today is": "Bugün",
  "Today, in one line": "Bugün, tek satırda",
  "Today:": "Bugün:",
  "Today's checklist —": "Bugünün kontrol listesi —",
  "Today's compliance": "Bugünkü uyum",
  "Token created — copy it now": "Anahtar oluşturuldu — şimdi kopyala",
  "Tomorrow": "Yarın",
  "Tomorrow · {}": "Yarın · {}",
  "Too many tries. Wait a minute and try again.": "Çok fazla deneme. Bir dakika bekle ve tekrar dene.",
  "Toplam": "Toplam",
  "Total": "Toplam",
  "Total completions": "Toplam tamamlama",
  "Total entries": "Toplam kayıt",
  "Total sessions": "Toplam seans",
  "Total spend per month, so a bad month is obvious before the next one starts.": "Ay başına toplam harcama, böylece kötü bir ay bir sonraki başlamadan belli olur.",
  "Total tasks": "Toplam görev",
  "Track daily habits across this week. Streaks reset if you miss a day.": "Bu hafta boyunca günlük alışkanlıkları takip et. Bir günü kaçırırsan seri sıfırlanır.",
  "Track monthly spending against your budget. Everything is local — nothing leaves your browser.": "Aylık harcamanı bütçene göre takip et. Her şey yerel — hiçbir şey tarayıcından çıkmaz.",
  "Track something else…": "Başka bir şey takip et…",
  "Train": "Çalış",
  "Train · {}": "Antrenman · {}",
  "Training": "Antrenman",
  "Training days": "Antrenman günleri",
  "Training week — one line per day, as": "Antrenman haftası — her güne bir satır, şu biçimde",
  "Transport": "Ulaşım",
  "Transport budget (£)": "Ulaşım bütçesi (£)",
  "Travel": "Seyahat",
  "Try again": "Tekrar dene",
  "Tue": "Sal",
  "Tuesday": "Salı",
  "Turn off to hide them everywhere without losing anything you already scheduled.": "Kapatmak, planladığın hiçbir şeyi kaybetmeden onları her yerde gizler.",
  "Turn the 🔔 on first.": "Önce 🔔 simgesini aç.",
  "Two minutes now beats reconstructing the week on Sunday.": "Şimdi iki dakika, Pazar günü haftayı baştan kurmaya bedeldir.",
  "Two or more periods needed for a trend.": "Bir eğilim için en az iki dönem gerekir.",
  "Type": "Tür",
  "Type a task first.": "Önce bir görev yaz.",
  "Type an email address.": "Bir e-posta adresi yaz.",
  "Type an email.": "Bir e-posta yaz.",
  "Type the code first.": "Önce kodu yaz.",
  "Type your email address first.": "Önce e-posta adresini yaz.",
  "Undo": "Geri al",
  "undo last": "sonuncuyu geri al",
  "Undo one": "Bir adım geri al",
  "Unique Solution": "Benzersiz Çözüm",
  "Unit": "Birim",
  "unit (sets, sessions…)": "birim (set, seans…)",
  "Unpair": "Eşleşmeyi bitir",
  "Unpair from {}": "{} ile eşleşmeyi bitir",
  "Unsaved changes…": "Kaydedilmemiş değişiklikler…",
  "Unscheduled": "Planlanmamış",
  "Unspent (savings)": "Harcanmayan (birikim)",
  "Untitled entry": "Başlıksız kayıt",
  "Update entry": "Kaydı güncelle",
  "Upgrade-pack data erased": "Yükseltme paketi verisi silindi",
  "Uploading {} data sets. On the free plan the server can take a moment to wake — this is normal.": "{} veri kümesi yükleniyor. Ücretsiz planda sunucunun uyanması biraz sürebilir — bu normaldir.",
  "Upper": "Üst",
  "Upper Body": "Üst Vücut",
  "urgent open": "acil açık",
  "Use at least 10 characters.": "En az 10 karakter kullan.",
  "Use one of your recovery codes. Each one works once.": "Kurtarma kodlarından birini kullan. Her biri bir kez çalışır.",
  "used {} days ago": "{} gün önce kullanıldı",
  "used today": "bugün kullanıldı",
  "used yesterday": "dün kullanıldı",
  "View": "Görünüm",
  "View raw text": "Ham metni gör",
  "violet night": "mor gece",
  "Virgo": "Başak",
  "Visual breakdown": "Görsel dağılım",
  "Waiting for Google sign-in…": "Google oturum açma bekleniyor…",
  "Wake time": "Uyanma saati",
  "warm light": "sıcak aydınlık",
  "Wed": "Çar",
  "Wednesday": "Çarşamba",
  "Week": "Hafta",
  "Week · Priorities · Training · Diet · Sleep & Mood · Habits · Money · Time · Journal": "Hafta · Öncelikler · Antrenman · Beslenme · Uyku ve Ruh Hali · Alışkanlıklar · Para · Zaman · Günlük",
  "Week {} · {}": "{1}. hafta · {2}",
  "Week {} · {} — this week": "{1}. hafta · {2} — bu hafta",
  "Week {} · {}{}": "{1}. hafta · {2}{3}",
  "Week Compass": "Hafta Pusulası",
  "Week completion": "Hafta tamamlanma",
  "Week starts": "Hafta başlangıcı",
  "Week streak (4+)": "Hafta serisi (4+)",
  "Weekly commitments (Sharpen the Blade) — one per line": "Haftalık taahhütler (Baltayı Bile) — her satıra bir tane",
  "Weekly progress": "Haftalık ilerleme",
  "Weekly rhythm": "Haftalık ritim",
  "weeks ago": "hafta önce",
  "Welcome back": "Tekrar hoş geldin",
  "What are the top 3-5 benefits your customer will experience?": "Müşterinin yaşayacağı en önemli 3-5 fayda nedir?",
  "What are you driving at work right now?": "Şu anda işte neyi sürüklüyorsun?",
  "What are your top 3 priorities for the next 3 months? Milestones and metrics?": "Önümüzdeki 3 ay için ilk 3 önceliğin ne? Kilometre taşları ve ölçütler?",
  "What core problem are you solving for people? Why does it matter?": "İnsanlar için hangi temel problemi çözüyorsun? Bu neden önemli?",
  "What do I do with the file?": "Dosyayla ne yapacağım?",
  "What does a good version of this week look like? The two or three things that would make it count, anything you're deliberately not doing, anyone you need to see…": "Bu haftanın iyi bir hâli nasıl görünür? Onu anlamlı kılacak iki üç şey, bilerek yapmadıkların, görmen gereken kişiler…",
  "What got in the way": "Ne engel oldu",
  "What happened?": "Ne oldu?",
  "What is this for? e.g. Claude on my laptop": "Bu ne için? ör. Dizüstümdeki Claude",
  "What is your origin story? Who are you, your background, experience, and what drives you?": "Hikâyen nasıl başladı? Kimsin, geçmişin, deneyimin ve seni ne sürüklüyor?",
  "What is your specific solution or approach? What makes it different from alternatives?": "Somut çözümün ya da yaklaşımın ne? Alternatiflerden farkı ne?",
  "What should I focus on this week?": "Bu hafta neye odaklanmalıyım?",
  "What should it call you?": "Sana nasıl seslensin?",
  "What the system recorded on {} — memory joggers": "Sistemin {} tarihinde kaydettikleri — hatırlatıcılar",
  "What they can see": "Ne görebilirler",
  "What went well": "Ne iyi gitti",
  "what you intend to do — in your own words": "ne yapmayı düşündüğün — kendi kelimelerinle",
  "What's the core problem you're solving? e.g. Finding the right audience for my product, scaling production without quality loss…": "Çözdüğün temel problem ne? ör. Ürünüm için doğru kitleyi bulmak, kaliteyi düşürmeden üretimi büyütmek…",
  "When": "Ne zaman",
  "Where {} went": "{} nereye gitti",
  "Where is my money going?": "Param nereye gidiyor?",
  "Where is this project headed?": "Bu proje nereye gidiyor?",
  "Where this is going": "Bu nereye gidiyor",
  "Where your data is being saved": "Verilerinin nereye kaydedildiği",
  "Who are the ideal customers for your solution? Describe them (age, job, pain points, etc).": "Çözümün için ideal müşteriler kim? Onları tarif et (yaş, iş, sıkıntılar vb.).",
  "Why not connect the bank directly?": "Neden bankaya doğrudan bağlanmıyoruz?",
  "Wins, lessons, what moves to next week...": "Kazanımlar, dersler, gelecek haftaya taşınanlar...",
  "Without them, a forgotten password means a lost account. Make a set now and keep them somewhere off this machine.": "Onlar olmadan unutulmuş bir parola kaybedilmiş bir hesap demektir. Şimdi bir set oluştur ve bu makinenin dışında bir yerde sakla.",
  "Words": "Kelime",
  "Work": "İş",
  "Work board {}": "İş panosu {}",
  "Working out where this is going…": "Bunun nereye gittiği çözülüyor…",
  "Workouts": "Antrenmanlar",
  "Worst night": "En kötü gece",
  "Start with what the week is for. Big Rocks are the few things that have to happen in it — the ones you would regret reaching Sunday without. A week fills up whether or not you choose what goes in it, so put these on a day first and let the small stuff fit around them; three to five is usually right. Use ← → to plan weeks ahead.": "Haftanın ne için olduğuyla başla. Büyük Kayalar, o hafta mutlaka olması gereken birkaç şeydir — pazar günü geldiğinde yapılmamış olmasına üzüleceğin şeyler. Bir hafta, sen seçsen de seçmesen de dolar; o yüzden önce bunları bir güne yerleştir, küçük işler etraflarına otursun. Üç ile beş arası genelde doğru sayıdır. İleriki haftaları planlamak için ← → kullan.",
  "Write here — it saves automatically and when you press Save notes.": "Buraya yaz — kendiliğinden ve Notları kaydet'e bastığında kaydedilir.",
  "Write something first.": "Önce bir şey yaz.",
  "Write today's direction.": "Bugünün yönünü yaz.",
  "Write today's entry": "Bugünün kaydını yaz",
  "Write what you plan to train that day. This applies only to the week you are viewing — use \"📋 Copy plan → next week\" to carry it forward.": "O gün ne çalışmayı planladığını yaz. Bu yalnızca baktığın hafta için geçerlidir — ileriye taşımak için \"📋 Planı kopyala → gelecek hafta\"yı kullan.",
  "Write who you are committed to being...": "Kim olmaya söz verdiğini yaz...",
  "Write your thoughts here...": "Düşüncelerini buraya yaz...",
  "Written journal entries (newest last)": "Yazılı günlük kayıtları (en yenisi sonda)",
  "Yes": "Evet",
  "Yesterday": "Dün",
  "You": "Sen",
  "You can still add the expense by hand below — the photo is kept if you save one now.": "Harcamayı aşağıdan elle de ekleyebilirsin — şimdi kaydedersen fotoğraf saklanır.",
  "You have no recovery codes.": "Hiç kurtarma kodun yok.",
  "You have not run one yet. It reads the last {} months of your own record — nothing to fill in.": "Henüz hiç çalıştırmadın. Kendi kaydının son {} ayını okur — doldurulacak bir şey yok.",
  "You have reached today's limit of {} messages. It resets at midnight UTC.": "Bugünkü {} mesaj sınırına ulaştın. UTC gece yarısı sıfırlanır.",
  "You have refreshed today's direction {} times. It resets at midnight UTC.": "Bugünün yönünü {} kez yeniledin. UTC gece yarısı sıfırlanır.",
  "You joined a shared task ✓": "Paylaşılan bir göreve katıldın ✓",
  "Your counts and streaks — the numbers, not the ledger.": "Sayıların ve serilerin — defter değil, rakamlar.",
  "Your current password:": "Mevcut parolan:",
  "Your data is private to your account.": "Verilerin hesabına özeldir.",
  "Your data is safe on this device, but it didn’t reach the cloud ({}). Make sure the top shows 🟢 Database, then tap Try again.": "Verilerin bu cihazda güvende ama buluta ulaşmadı ({}). Üstte 🟢 Veritabanı yazdığından emin ol, sonra Tekrar dene'ye dokun.",
  "Your day": "Günün",
  "your friend": "arkadaşın",
  "Your job or main business — the goal you are driving, the tasks in motion, and a running log.": "İşin ya da ana işletmen — sürdüğün hedef, hareket hâlindeki görevler ve akan bir kayıt.",
  "Your new password — at least 10 characters": "Yeni parolan — en az 10 karakter",
  "Your new token — copy it now, it is not shown again": "Yeni anahtarın — şimdi kopyala, bir daha gösterilmez",
  "Your own name for it": "Buna kendi verdiğin ad",
  "Your own project — north-star goal, task pipeline, and notes.": "Kendi projen — kuzey yıldızı hedefi, görev hattı ve notlar.",
  "Your recovery codes": "Kurtarma kodların",
  "Your words · not an activity feed": "Senin kelimelerin · bir etkinlik akışı değil",
  "zero is a choice, and worth naming as one.": "sıfır da bir tercihtir ve öyle adlandırılmayı hak eder.",
  "🎤 Voice": "🎤 Ses",
  "Voice": "Ses",
  "Dictate": "Dikte et",
  "Listening…": "Dinliyor…",
  "Checking…": "Kontrol ediliyor…",
  "The microphone is blocked. Allow it for this site and try again.": "Mikrofon engellenmiş. Bu site için izin ver ve tekrar dene.",
  "I didn't hear anything.": "Hiçbir şey duymadım.",
  "Dictation needs a connection right now.": "Dikte şu anda bağlantı gerektiriyor.",
  "No microphone found.": "Mikrofon bulunamadı.",
  "Dictation is not available on this device.": "Bu cihazda dikte kullanılamıyor.",
  "That did not work. Try again.": "Bu işe yaramadı. Tekrar dene.",
  "A microphone appears in the corner of whatever you are writing in. Tap it, talk, tap it again — the words land where your cursor was. It listens in the language the app is set to, so switching to Turkish switches the dictation too.": "Yazdığın her alanın köşesinde bir mikrofon belirir. Dokun, konuş, tekrar dokun — kelimeler imlecin olduğu yere gelir. Uygulamanın dilinde dinler, yani Türkçe'ye geçince dikte de Türkçe olur.",
  "Your phone's own keyboard mic and tools like Wispr Flow type straight into these fields and work here too — nothing needs turning on for those.": "Telefonunun kendi klavye mikrofonu ve Wispr Flow gibi araçlar doğrudan bu alanlara yazar ve burada da çalışır — onlar için bir şey açman gerekmez.",
  "Allow the microphone": "Mikrofona izin ver",
  "Not available in this browser": "Bu tarayıcıda kullanılamıyor",
  "Chrome, Edge and Safari can do this; Firefox cannot yet. On your phone the app itself can, so it works there.": "Chrome, Edge ve Safari bunu yapabilir; Firefox henüz yapamıyor. Telefonunda uygulamanın kendisi yapabildiği için orada çalışır.",
  "Ready": "Hazır",
  "Your browser will ask for the microphone the first time you press it.": "Tarayıcın ilk bastığında mikrofon izni isteyecek.",
  "Allowed": "İzin verildi",
  "The microphone and speech recognition are both on.": "Mikrofon ve konuşma tanıma açık.",
  "Turn the microphone and speech recognition back on for The Flow in your iPhone Settings — the app cannot ask again once they have been refused.": "iPhone Ayarlar'ından The Flow için mikrofonu ve konuşma tanımayı tekrar aç — bir kez reddedildikten sonra uygulama bir daha soramaz.",
  "Not asked yet": "Henüz sorulmadı",
  "The Flow needs the microphone to hear you, and speech recognition to turn it into words.": "The Flow seni duymak için mikrofona, söylediklerini yazıya çevirmek için konuşma tanımaya ihtiyaç duyar.",
/* DICT-END */
}, RULES);

})();
